        
 DELETE FROM BIZ_WORKFLOW_PROJECT WHERE PID IN(     
 SELECT B.PID
   FROM BIZ_WORKFLOW_PROJECT B,
        (SELECT A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY, COUNT(*)
           FROM BIZ_WORKFLOW_PROJECT A
          GROUP BY A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY
         HAVING COUNT(*) > 1) A
  WHERE A.PROJECT_ID = B.PROJECT_ID
    AND A.PROCESS_DEFINITION_KEY = B.PROCESS_DEFINITION_KEY
    AND A.REF_ID = B.REF_ID
    AND B.PID NOT IN
        (SELECT MAX(A.PID)
           FROM BIZ_WORKFLOW_PROJECT A
          GROUP BY A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY
         HAVING COUNT(*) > 1));


alter table BIZ_WORKFLOW_PROJECT_OTHER
  add constraint UNIQUE_BIZ_WORKFLOW_PROJECT unique (REF_ID, WORKFLOW_INSTANCE_ID,project_id);