--同步机构信息到收费下拉框中
CREATE OR REPLACE TRIGGER TRIG_ORG_LOOKUP
  AFTER INSERT ON ORG_ASSETS_COOPERATION_INFO
  FOR EACH ROW
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM SYS_LOOKUP_VAL A WHERE A.LOOKUP_ID=10544
   AND A.LOOKUP_DESC = :NEW.ORG_NAME;
  IF V_COUNT=0 THEN
   INSERT INTO SYS_LOOKUP_VAL (PID,STATUS,LOOKUP_ID,LOOKUP_VAL,LOOKUP_DESC) 
   VALUES(SEQ_SYS_LOOKUP_VAL.NEXTVAL,1,10544,:NEW.ORG_NAME,:NEW.ORG_NAME);
  END IF;
END TRIG_ORG_LOOKUP;
--机构信息变更后更新数据字典的值
CREATE OR REPLACE TRIGGER TRIG_ORG_LOOKUP_UPDATE
  AFTER UPDATE OF ORG_NAME ON ORG_ASSETS_COOPERATION_INFO
  FOR EACH ROW
DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM SYS_LOOKUP_VAL A WHERE A.LOOKUP_ID=10544
   AND A.LOOKUP_DESC = :OLD.ORG_NAME;
  IF V_COUNT=0 THEN
   INSERT INTO SYS_LOOKUP_VAL (PID,STATUS,LOOKUP_ID,LOOKUP_VAL,LOOKUP_DESC) 
   VALUES(SEQ_SYS_LOOKUP_VAL.NEXTVAL,1,10544,:NEW.ORG_NAME,:NEW.ORG_NAME);
  END IF;
  IF V_COUNT=1 THEN
    UPDATE SYS_LOOKUP_VAL A SET A.LOOKUP_DESC = :NEW.ORG_NAME WHERE A.LOOKUP_ID = 10544 AND A.LOOKUP_DESC=:OLD.ORG_NAME;
   END IF; 
END TRIG_ORG_LOOKUP_UPDATE;