/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xlkfinance.bms.rpc.inloan;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2018-1-11")
public class HandleDifferWarnDTO implements org.apache.thrift.TBase<HandleDifferWarnDTO, HandleDifferWarnDTO._Fields>, java.io.Serializable, Cloneable, Comparable<HandleDifferWarnDTO> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HandleDifferWarnDTO");

  private static final org.apache.thrift.protocol.TField PID_FIELD_DESC = new org.apache.thrift.protocol.TField("pid", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField HANDLE_DYNAMIC_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("handleDynamicId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField DIFFER_FIELD_DESC = new org.apache.thrift.protocol.TField("differ", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField HANDLE_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("handleDate", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField HANDLE_AUTHOR_FIELD_DESC = new org.apache.thrift.protocol.TField("handleAuthor", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField CREATE_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("createDate", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField REMARK_FIELD_DESC = new org.apache.thrift.protocol.TField("remark", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField USER_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("userIds", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("page", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField ROWS_FIELD_DESC = new org.apache.thrift.protocol.TField("rows", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField PROJECT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("projectId", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField PROJECT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("projectName", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField FLOW_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("flowName", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField HANDLE_AUTHOR_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("handleAuthorName", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField HANDLE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("handleType", org.apache.thrift.protocol.TType.I32, (short)16);
  private static final org.apache.thrift.protocol.TField FLOW_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("flowId", org.apache.thrift.protocol.TType.I32, (short)17);
  private static final org.apache.thrift.protocol.TField HANDLE_TYPE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("handleTypeList", org.apache.thrift.protocol.TType.LIST, (short)18);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HandleDifferWarnDTOStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HandleDifferWarnDTOTupleSchemeFactory());
  }

  public int pid; // required
  public int handleDynamicId; // required
  public int differ; // required
  public int status; // required
  public String handleDate; // required
  public int handleAuthor; // required
  public String createDate; // required
  public String remark; // required
  public List<Integer> userIds; // required
  public int page; // required
  public int rows; // required
  public int projectId; // required
  public String projectName; // required
  public String flowName; // required
  public String handleAuthorName; // required
  public int handleType; // required
  public int flowId; // required
  public List<Integer> handleTypeList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PID((short)1, "pid"),
    HANDLE_DYNAMIC_ID((short)2, "handleDynamicId"),
    DIFFER((short)3, "differ"),
    STATUS((short)4, "status"),
    HANDLE_DATE((short)5, "handleDate"),
    HANDLE_AUTHOR((short)6, "handleAuthor"),
    CREATE_DATE((short)7, "createDate"),
    REMARK((short)8, "remark"),
    USER_IDS((short)9, "userIds"),
    PAGE((short)10, "page"),
    ROWS((short)11, "rows"),
    PROJECT_ID((short)12, "projectId"),
    PROJECT_NAME((short)13, "projectName"),
    FLOW_NAME((short)14, "flowName"),
    HANDLE_AUTHOR_NAME((short)15, "handleAuthorName"),
    HANDLE_TYPE((short)16, "handleType"),
    FLOW_ID((short)17, "flowId"),
    HANDLE_TYPE_LIST((short)18, "handleTypeList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PID
          return PID;
        case 2: // HANDLE_DYNAMIC_ID
          return HANDLE_DYNAMIC_ID;
        case 3: // DIFFER
          return DIFFER;
        case 4: // STATUS
          return STATUS;
        case 5: // HANDLE_DATE
          return HANDLE_DATE;
        case 6: // HANDLE_AUTHOR
          return HANDLE_AUTHOR;
        case 7: // CREATE_DATE
          return CREATE_DATE;
        case 8: // REMARK
          return REMARK;
        case 9: // USER_IDS
          return USER_IDS;
        case 10: // PAGE
          return PAGE;
        case 11: // ROWS
          return ROWS;
        case 12: // PROJECT_ID
          return PROJECT_ID;
        case 13: // PROJECT_NAME
          return PROJECT_NAME;
        case 14: // FLOW_NAME
          return FLOW_NAME;
        case 15: // HANDLE_AUTHOR_NAME
          return HANDLE_AUTHOR_NAME;
        case 16: // HANDLE_TYPE
          return HANDLE_TYPE;
        case 17: // FLOW_ID
          return FLOW_ID;
        case 18: // HANDLE_TYPE_LIST
          return HANDLE_TYPE_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PID_ISSET_ID = 0;
  private static final int __HANDLEDYNAMICID_ISSET_ID = 1;
  private static final int __DIFFER_ISSET_ID = 2;
  private static final int __STATUS_ISSET_ID = 3;
  private static final int __HANDLEAUTHOR_ISSET_ID = 4;
  private static final int __PAGE_ISSET_ID = 5;
  private static final int __ROWS_ISSET_ID = 6;
  private static final int __PROJECTID_ISSET_ID = 7;
  private static final int __HANDLETYPE_ISSET_ID = 8;
  private static final int __FLOWID_ISSET_ID = 9;
  private short __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PID, new org.apache.thrift.meta_data.FieldMetaData("pid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HANDLE_DYNAMIC_ID, new org.apache.thrift.meta_data.FieldMetaData("handleDynamicId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DIFFER, new org.apache.thrift.meta_data.FieldMetaData("differ", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HANDLE_DATE, new org.apache.thrift.meta_data.FieldMetaData("handleDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HANDLE_AUTHOR, new org.apache.thrift.meta_data.FieldMetaData("handleAuthor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATE_DATE, new org.apache.thrift.meta_data.FieldMetaData("createDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REMARK, new org.apache.thrift.meta_data.FieldMetaData("remark", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USER_IDS, new org.apache.thrift.meta_data.FieldMetaData("userIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.PAGE, new org.apache.thrift.meta_data.FieldMetaData("page", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ROWS, new org.apache.thrift.meta_data.FieldMetaData("rows", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PROJECT_ID, new org.apache.thrift.meta_data.FieldMetaData("projectId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PROJECT_NAME, new org.apache.thrift.meta_data.FieldMetaData("projectName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FLOW_NAME, new org.apache.thrift.meta_data.FieldMetaData("flowName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HANDLE_AUTHOR_NAME, new org.apache.thrift.meta_data.FieldMetaData("handleAuthorName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HANDLE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("handleType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FLOW_ID, new org.apache.thrift.meta_data.FieldMetaData("flowId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HANDLE_TYPE_LIST, new org.apache.thrift.meta_data.FieldMetaData("handleTypeList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HandleDifferWarnDTO.class, metaDataMap);
  }

  public HandleDifferWarnDTO() {
    this.page = 1;

    this.rows = 10;

  }

  public HandleDifferWarnDTO(
    int pid,
    int handleDynamicId,
    int differ,
    int status,
    String handleDate,
    int handleAuthor,
    String createDate,
    String remark,
    List<Integer> userIds,
    int page,
    int rows,
    int projectId,
    String projectName,
    String flowName,
    String handleAuthorName,
    int handleType,
    int flowId,
    List<Integer> handleTypeList)
  {
    this();
    this.pid = pid;
    setPidIsSet(true);
    this.handleDynamicId = handleDynamicId;
    setHandleDynamicIdIsSet(true);
    this.differ = differ;
    setDifferIsSet(true);
    this.status = status;
    setStatusIsSet(true);
    this.handleDate = handleDate;
    this.handleAuthor = handleAuthor;
    setHandleAuthorIsSet(true);
    this.createDate = createDate;
    this.remark = remark;
    this.userIds = userIds;
    this.page = page;
    setPageIsSet(true);
    this.rows = rows;
    setRowsIsSet(true);
    this.projectId = projectId;
    setProjectIdIsSet(true);
    this.projectName = projectName;
    this.flowName = flowName;
    this.handleAuthorName = handleAuthorName;
    this.handleType = handleType;
    setHandleTypeIsSet(true);
    this.flowId = flowId;
    setFlowIdIsSet(true);
    this.handleTypeList = handleTypeList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HandleDifferWarnDTO(HandleDifferWarnDTO other) {
    __isset_bitfield = other.__isset_bitfield;
    this.pid = other.pid;
    this.handleDynamicId = other.handleDynamicId;
    this.differ = other.differ;
    this.status = other.status;
    if (other.isSetHandleDate()) {
      this.handleDate = other.handleDate;
    }
    this.handleAuthor = other.handleAuthor;
    if (other.isSetCreateDate()) {
      this.createDate = other.createDate;
    }
    if (other.isSetRemark()) {
      this.remark = other.remark;
    }
    if (other.isSetUserIds()) {
      List<Integer> __this__userIds = new ArrayList<Integer>(other.userIds);
      this.userIds = __this__userIds;
    }
    this.page = other.page;
    this.rows = other.rows;
    this.projectId = other.projectId;
    if (other.isSetProjectName()) {
      this.projectName = other.projectName;
    }
    if (other.isSetFlowName()) {
      this.flowName = other.flowName;
    }
    if (other.isSetHandleAuthorName()) {
      this.handleAuthorName = other.handleAuthorName;
    }
    this.handleType = other.handleType;
    this.flowId = other.flowId;
    if (other.isSetHandleTypeList()) {
      List<Integer> __this__handleTypeList = new ArrayList<Integer>(other.handleTypeList);
      this.handleTypeList = __this__handleTypeList;
    }
  }

  public HandleDifferWarnDTO deepCopy() {
    return new HandleDifferWarnDTO(this);
  }

  @Override
  public void clear() {
    setPidIsSet(false);
    this.pid = 0;
    setHandleDynamicIdIsSet(false);
    this.handleDynamicId = 0;
    setDifferIsSet(false);
    this.differ = 0;
    setStatusIsSet(false);
    this.status = 0;
    this.handleDate = null;
    setHandleAuthorIsSet(false);
    this.handleAuthor = 0;
    this.createDate = null;
    this.remark = null;
    this.userIds = null;
    this.page = 1;

    this.rows = 10;

    setProjectIdIsSet(false);
    this.projectId = 0;
    this.projectName = null;
    this.flowName = null;
    this.handleAuthorName = null;
    setHandleTypeIsSet(false);
    this.handleType = 0;
    setFlowIdIsSet(false);
    this.flowId = 0;
    this.handleTypeList = null;
  }

  public int getPid() {
    return this.pid;
  }

  public HandleDifferWarnDTO setPid(int pid) {
    this.pid = pid;
    setPidIsSet(true);
    return this;
  }

  public void unsetPid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PID_ISSET_ID);
  }

  /** Returns true if field pid is set (has been assigned a value) and false otherwise */
  public boolean isSetPid() {
    return EncodingUtils.testBit(__isset_bitfield, __PID_ISSET_ID);
  }

  public void setPidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PID_ISSET_ID, value);
  }

  public int getHandleDynamicId() {
    return this.handleDynamicId;
  }

  public HandleDifferWarnDTO setHandleDynamicId(int handleDynamicId) {
    this.handleDynamicId = handleDynamicId;
    setHandleDynamicIdIsSet(true);
    return this;
  }

  public void unsetHandleDynamicId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HANDLEDYNAMICID_ISSET_ID);
  }

  /** Returns true if field handleDynamicId is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleDynamicId() {
    return EncodingUtils.testBit(__isset_bitfield, __HANDLEDYNAMICID_ISSET_ID);
  }

  public void setHandleDynamicIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HANDLEDYNAMICID_ISSET_ID, value);
  }

  public int getDiffer() {
    return this.differ;
  }

  public HandleDifferWarnDTO setDiffer(int differ) {
    this.differ = differ;
    setDifferIsSet(true);
    return this;
  }

  public void unsetDiffer() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DIFFER_ISSET_ID);
  }

  /** Returns true if field differ is set (has been assigned a value) and false otherwise */
  public boolean isSetDiffer() {
    return EncodingUtils.testBit(__isset_bitfield, __DIFFER_ISSET_ID);
  }

  public void setDifferIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DIFFER_ISSET_ID, value);
  }

  public int getStatus() {
    return this.status;
  }

  public HandleDifferWarnDTO setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public String getHandleDate() {
    return this.handleDate;
  }

  public HandleDifferWarnDTO setHandleDate(String handleDate) {
    this.handleDate = handleDate;
    return this;
  }

  public void unsetHandleDate() {
    this.handleDate = null;
  }

  /** Returns true if field handleDate is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleDate() {
    return this.handleDate != null;
  }

  public void setHandleDateIsSet(boolean value) {
    if (!value) {
      this.handleDate = null;
    }
  }

  public int getHandleAuthor() {
    return this.handleAuthor;
  }

  public HandleDifferWarnDTO setHandleAuthor(int handleAuthor) {
    this.handleAuthor = handleAuthor;
    setHandleAuthorIsSet(true);
    return this;
  }

  public void unsetHandleAuthor() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HANDLEAUTHOR_ISSET_ID);
  }

  /** Returns true if field handleAuthor is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleAuthor() {
    return EncodingUtils.testBit(__isset_bitfield, __HANDLEAUTHOR_ISSET_ID);
  }

  public void setHandleAuthorIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HANDLEAUTHOR_ISSET_ID, value);
  }

  public String getCreateDate() {
    return this.createDate;
  }

  public HandleDifferWarnDTO setCreateDate(String createDate) {
    this.createDate = createDate;
    return this;
  }

  public void unsetCreateDate() {
    this.createDate = null;
  }

  /** Returns true if field createDate is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateDate() {
    return this.createDate != null;
  }

  public void setCreateDateIsSet(boolean value) {
    if (!value) {
      this.createDate = null;
    }
  }

  public String getRemark() {
    return this.remark;
  }

  public HandleDifferWarnDTO setRemark(String remark) {
    this.remark = remark;
    return this;
  }

  public void unsetRemark() {
    this.remark = null;
  }

  /** Returns true if field remark is set (has been assigned a value) and false otherwise */
  public boolean isSetRemark() {
    return this.remark != null;
  }

  public void setRemarkIsSet(boolean value) {
    if (!value) {
      this.remark = null;
    }
  }

  public int getUserIdsSize() {
    return (this.userIds == null) ? 0 : this.userIds.size();
  }

  public java.util.Iterator<Integer> getUserIdsIterator() {
    return (this.userIds == null) ? null : this.userIds.iterator();
  }

  public void addToUserIds(int elem) {
    if (this.userIds == null) {
      this.userIds = new ArrayList<Integer>();
    }
    this.userIds.add(elem);
  }

  public List<Integer> getUserIds() {
    return this.userIds;
  }

  public HandleDifferWarnDTO setUserIds(List<Integer> userIds) {
    this.userIds = userIds;
    return this;
  }

  public void unsetUserIds() {
    this.userIds = null;
  }

  /** Returns true if field userIds is set (has been assigned a value) and false otherwise */
  public boolean isSetUserIds() {
    return this.userIds != null;
  }

  public void setUserIdsIsSet(boolean value) {
    if (!value) {
      this.userIds = null;
    }
  }

  public int getPage() {
    return this.page;
  }

  public HandleDifferWarnDTO setPage(int page) {
    this.page = page;
    setPageIsSet(true);
    return this;
  }

  public void unsetPage() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PAGE_ISSET_ID);
  }

  /** Returns true if field page is set (has been assigned a value) and false otherwise */
  public boolean isSetPage() {
    return EncodingUtils.testBit(__isset_bitfield, __PAGE_ISSET_ID);
  }

  public void setPageIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PAGE_ISSET_ID, value);
  }

  public int getRows() {
    return this.rows;
  }

  public HandleDifferWarnDTO setRows(int rows) {
    this.rows = rows;
    setRowsIsSet(true);
    return this;
  }

  public void unsetRows() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ROWS_ISSET_ID);
  }

  /** Returns true if field rows is set (has been assigned a value) and false otherwise */
  public boolean isSetRows() {
    return EncodingUtils.testBit(__isset_bitfield, __ROWS_ISSET_ID);
  }

  public void setRowsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ROWS_ISSET_ID, value);
  }

  public int getProjectId() {
    return this.projectId;
  }

  public HandleDifferWarnDTO setProjectId(int projectId) {
    this.projectId = projectId;
    setProjectIdIsSet(true);
    return this;
  }

  public void unsetProjectId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PROJECTID_ISSET_ID);
  }

  /** Returns true if field projectId is set (has been assigned a value) and false otherwise */
  public boolean isSetProjectId() {
    return EncodingUtils.testBit(__isset_bitfield, __PROJECTID_ISSET_ID);
  }

  public void setProjectIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PROJECTID_ISSET_ID, value);
  }

  public String getProjectName() {
    return this.projectName;
  }

  public HandleDifferWarnDTO setProjectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

  public void unsetProjectName() {
    this.projectName = null;
  }

  /** Returns true if field projectName is set (has been assigned a value) and false otherwise */
  public boolean isSetProjectName() {
    return this.projectName != null;
  }

  public void setProjectNameIsSet(boolean value) {
    if (!value) {
      this.projectName = null;
    }
  }

  public String getFlowName() {
    return this.flowName;
  }

  public HandleDifferWarnDTO setFlowName(String flowName) {
    this.flowName = flowName;
    return this;
  }

  public void unsetFlowName() {
    this.flowName = null;
  }

  /** Returns true if field flowName is set (has been assigned a value) and false otherwise */
  public boolean isSetFlowName() {
    return this.flowName != null;
  }

  public void setFlowNameIsSet(boolean value) {
    if (!value) {
      this.flowName = null;
    }
  }

  public String getHandleAuthorName() {
    return this.handleAuthorName;
  }

  public HandleDifferWarnDTO setHandleAuthorName(String handleAuthorName) {
    this.handleAuthorName = handleAuthorName;
    return this;
  }

  public void unsetHandleAuthorName() {
    this.handleAuthorName = null;
  }

  /** Returns true if field handleAuthorName is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleAuthorName() {
    return this.handleAuthorName != null;
  }

  public void setHandleAuthorNameIsSet(boolean value) {
    if (!value) {
      this.handleAuthorName = null;
    }
  }

  public int getHandleType() {
    return this.handleType;
  }

  public HandleDifferWarnDTO setHandleType(int handleType) {
    this.handleType = handleType;
    setHandleTypeIsSet(true);
    return this;
  }

  public void unsetHandleType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HANDLETYPE_ISSET_ID);
  }

  /** Returns true if field handleType is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleType() {
    return EncodingUtils.testBit(__isset_bitfield, __HANDLETYPE_ISSET_ID);
  }

  public void setHandleTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HANDLETYPE_ISSET_ID, value);
  }

  public int getFlowId() {
    return this.flowId;
  }

  public HandleDifferWarnDTO setFlowId(int flowId) {
    this.flowId = flowId;
    setFlowIdIsSet(true);
    return this;
  }

  public void unsetFlowId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FLOWID_ISSET_ID);
  }

  /** Returns true if field flowId is set (has been assigned a value) and false otherwise */
  public boolean isSetFlowId() {
    return EncodingUtils.testBit(__isset_bitfield, __FLOWID_ISSET_ID);
  }

  public void setFlowIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FLOWID_ISSET_ID, value);
  }

  public int getHandleTypeListSize() {
    return (this.handleTypeList == null) ? 0 : this.handleTypeList.size();
  }

  public java.util.Iterator<Integer> getHandleTypeListIterator() {
    return (this.handleTypeList == null) ? null : this.handleTypeList.iterator();
  }

  public void addToHandleTypeList(int elem) {
    if (this.handleTypeList == null) {
      this.handleTypeList = new ArrayList<Integer>();
    }
    this.handleTypeList.add(elem);
  }

  public List<Integer> getHandleTypeList() {
    return this.handleTypeList;
  }

  public HandleDifferWarnDTO setHandleTypeList(List<Integer> handleTypeList) {
    this.handleTypeList = handleTypeList;
    return this;
  }

  public void unsetHandleTypeList() {
    this.handleTypeList = null;
  }

  /** Returns true if field handleTypeList is set (has been assigned a value) and false otherwise */
  public boolean isSetHandleTypeList() {
    return this.handleTypeList != null;
  }

  public void setHandleTypeListIsSet(boolean value) {
    if (!value) {
      this.handleTypeList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PID:
      if (value == null) {
        unsetPid();
      } else {
        setPid((Integer)value);
      }
      break;

    case HANDLE_DYNAMIC_ID:
      if (value == null) {
        unsetHandleDynamicId();
      } else {
        setHandleDynamicId((Integer)value);
      }
      break;

    case DIFFER:
      if (value == null) {
        unsetDiffer();
      } else {
        setDiffer((Integer)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case HANDLE_DATE:
      if (value == null) {
        unsetHandleDate();
      } else {
        setHandleDate((String)value);
      }
      break;

    case HANDLE_AUTHOR:
      if (value == null) {
        unsetHandleAuthor();
      } else {
        setHandleAuthor((Integer)value);
      }
      break;

    case CREATE_DATE:
      if (value == null) {
        unsetCreateDate();
      } else {
        setCreateDate((String)value);
      }
      break;

    case REMARK:
      if (value == null) {
        unsetRemark();
      } else {
        setRemark((String)value);
      }
      break;

    case USER_IDS:
      if (value == null) {
        unsetUserIds();
      } else {
        setUserIds((List<Integer>)value);
      }
      break;

    case PAGE:
      if (value == null) {
        unsetPage();
      } else {
        setPage((Integer)value);
      }
      break;

    case ROWS:
      if (value == null) {
        unsetRows();
      } else {
        setRows((Integer)value);
      }
      break;

    case PROJECT_ID:
      if (value == null) {
        unsetProjectId();
      } else {
        setProjectId((Integer)value);
      }
      break;

    case PROJECT_NAME:
      if (value == null) {
        unsetProjectName();
      } else {
        setProjectName((String)value);
      }
      break;

    case FLOW_NAME:
      if (value == null) {
        unsetFlowName();
      } else {
        setFlowName((String)value);
      }
      break;

    case HANDLE_AUTHOR_NAME:
      if (value == null) {
        unsetHandleAuthorName();
      } else {
        setHandleAuthorName((String)value);
      }
      break;

    case HANDLE_TYPE:
      if (value == null) {
        unsetHandleType();
      } else {
        setHandleType((Integer)value);
      }
      break;

    case FLOW_ID:
      if (value == null) {
        unsetFlowId();
      } else {
        setFlowId((Integer)value);
      }
      break;

    case HANDLE_TYPE_LIST:
      if (value == null) {
        unsetHandleTypeList();
      } else {
        setHandleTypeList((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PID:
      return Integer.valueOf(getPid());

    case HANDLE_DYNAMIC_ID:
      return Integer.valueOf(getHandleDynamicId());

    case DIFFER:
      return Integer.valueOf(getDiffer());

    case STATUS:
      return Integer.valueOf(getStatus());

    case HANDLE_DATE:
      return getHandleDate();

    case HANDLE_AUTHOR:
      return Integer.valueOf(getHandleAuthor());

    case CREATE_DATE:
      return getCreateDate();

    case REMARK:
      return getRemark();

    case USER_IDS:
      return getUserIds();

    case PAGE:
      return Integer.valueOf(getPage());

    case ROWS:
      return Integer.valueOf(getRows());

    case PROJECT_ID:
      return Integer.valueOf(getProjectId());

    case PROJECT_NAME:
      return getProjectName();

    case FLOW_NAME:
      return getFlowName();

    case HANDLE_AUTHOR_NAME:
      return getHandleAuthorName();

    case HANDLE_TYPE:
      return Integer.valueOf(getHandleType());

    case FLOW_ID:
      return Integer.valueOf(getFlowId());

    case HANDLE_TYPE_LIST:
      return getHandleTypeList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PID:
      return isSetPid();
    case HANDLE_DYNAMIC_ID:
      return isSetHandleDynamicId();
    case DIFFER:
      return isSetDiffer();
    case STATUS:
      return isSetStatus();
    case HANDLE_DATE:
      return isSetHandleDate();
    case HANDLE_AUTHOR:
      return isSetHandleAuthor();
    case CREATE_DATE:
      return isSetCreateDate();
    case REMARK:
      return isSetRemark();
    case USER_IDS:
      return isSetUserIds();
    case PAGE:
      return isSetPage();
    case ROWS:
      return isSetRows();
    case PROJECT_ID:
      return isSetProjectId();
    case PROJECT_NAME:
      return isSetProjectName();
    case FLOW_NAME:
      return isSetFlowName();
    case HANDLE_AUTHOR_NAME:
      return isSetHandleAuthorName();
    case HANDLE_TYPE:
      return isSetHandleType();
    case FLOW_ID:
      return isSetFlowId();
    case HANDLE_TYPE_LIST:
      return isSetHandleTypeList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HandleDifferWarnDTO)
      return this.equals((HandleDifferWarnDTO)that);
    return false;
  }

  public boolean equals(HandleDifferWarnDTO that) {
    if (that == null)
      return false;

    boolean this_present_pid = true;
    boolean that_present_pid = true;
    if (this_present_pid || that_present_pid) {
      if (!(this_present_pid && that_present_pid))
        return false;
      if (this.pid != that.pid)
        return false;
    }

    boolean this_present_handleDynamicId = true;
    boolean that_present_handleDynamicId = true;
    if (this_present_handleDynamicId || that_present_handleDynamicId) {
      if (!(this_present_handleDynamicId && that_present_handleDynamicId))
        return false;
      if (this.handleDynamicId != that.handleDynamicId)
        return false;
    }

    boolean this_present_differ = true;
    boolean that_present_differ = true;
    if (this_present_differ || that_present_differ) {
      if (!(this_present_differ && that_present_differ))
        return false;
      if (this.differ != that.differ)
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_handleDate = true && this.isSetHandleDate();
    boolean that_present_handleDate = true && that.isSetHandleDate();
    if (this_present_handleDate || that_present_handleDate) {
      if (!(this_present_handleDate && that_present_handleDate))
        return false;
      if (!this.handleDate.equals(that.handleDate))
        return false;
    }

    boolean this_present_handleAuthor = true;
    boolean that_present_handleAuthor = true;
    if (this_present_handleAuthor || that_present_handleAuthor) {
      if (!(this_present_handleAuthor && that_present_handleAuthor))
        return false;
      if (this.handleAuthor != that.handleAuthor)
        return false;
    }

    boolean this_present_createDate = true && this.isSetCreateDate();
    boolean that_present_createDate = true && that.isSetCreateDate();
    if (this_present_createDate || that_present_createDate) {
      if (!(this_present_createDate && that_present_createDate))
        return false;
      if (!this.createDate.equals(that.createDate))
        return false;
    }

    boolean this_present_remark = true && this.isSetRemark();
    boolean that_present_remark = true && that.isSetRemark();
    if (this_present_remark || that_present_remark) {
      if (!(this_present_remark && that_present_remark))
        return false;
      if (!this.remark.equals(that.remark))
        return false;
    }

    boolean this_present_userIds = true && this.isSetUserIds();
    boolean that_present_userIds = true && that.isSetUserIds();
    if (this_present_userIds || that_present_userIds) {
      if (!(this_present_userIds && that_present_userIds))
        return false;
      if (!this.userIds.equals(that.userIds))
        return false;
    }

    boolean this_present_page = true;
    boolean that_present_page = true;
    if (this_present_page || that_present_page) {
      if (!(this_present_page && that_present_page))
        return false;
      if (this.page != that.page)
        return false;
    }

    boolean this_present_rows = true;
    boolean that_present_rows = true;
    if (this_present_rows || that_present_rows) {
      if (!(this_present_rows && that_present_rows))
        return false;
      if (this.rows != that.rows)
        return false;
    }

    boolean this_present_projectId = true;
    boolean that_present_projectId = true;
    if (this_present_projectId || that_present_projectId) {
      if (!(this_present_projectId && that_present_projectId))
        return false;
      if (this.projectId != that.projectId)
        return false;
    }

    boolean this_present_projectName = true && this.isSetProjectName();
    boolean that_present_projectName = true && that.isSetProjectName();
    if (this_present_projectName || that_present_projectName) {
      if (!(this_present_projectName && that_present_projectName))
        return false;
      if (!this.projectName.equals(that.projectName))
        return false;
    }

    boolean this_present_flowName = true && this.isSetFlowName();
    boolean that_present_flowName = true && that.isSetFlowName();
    if (this_present_flowName || that_present_flowName) {
      if (!(this_present_flowName && that_present_flowName))
        return false;
      if (!this.flowName.equals(that.flowName))
        return false;
    }

    boolean this_present_handleAuthorName = true && this.isSetHandleAuthorName();
    boolean that_present_handleAuthorName = true && that.isSetHandleAuthorName();
    if (this_present_handleAuthorName || that_present_handleAuthorName) {
      if (!(this_present_handleAuthorName && that_present_handleAuthorName))
        return false;
      if (!this.handleAuthorName.equals(that.handleAuthorName))
        return false;
    }

    boolean this_present_handleType = true;
    boolean that_present_handleType = true;
    if (this_present_handleType || that_present_handleType) {
      if (!(this_present_handleType && that_present_handleType))
        return false;
      if (this.handleType != that.handleType)
        return false;
    }

    boolean this_present_flowId = true;
    boolean that_present_flowId = true;
    if (this_present_flowId || that_present_flowId) {
      if (!(this_present_flowId && that_present_flowId))
        return false;
      if (this.flowId != that.flowId)
        return false;
    }

    boolean this_present_handleTypeList = true && this.isSetHandleTypeList();
    boolean that_present_handleTypeList = true && that.isSetHandleTypeList();
    if (this_present_handleTypeList || that_present_handleTypeList) {
      if (!(this_present_handleTypeList && that_present_handleTypeList))
        return false;
      if (!this.handleTypeList.equals(that.handleTypeList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_pid = true;
    list.add(present_pid);
    if (present_pid)
      list.add(pid);

    boolean present_handleDynamicId = true;
    list.add(present_handleDynamicId);
    if (present_handleDynamicId)
      list.add(handleDynamicId);

    boolean present_differ = true;
    list.add(present_differ);
    if (present_differ)
      list.add(differ);

    boolean present_status = true;
    list.add(present_status);
    if (present_status)
      list.add(status);

    boolean present_handleDate = true && (isSetHandleDate());
    list.add(present_handleDate);
    if (present_handleDate)
      list.add(handleDate);

    boolean present_handleAuthor = true;
    list.add(present_handleAuthor);
    if (present_handleAuthor)
      list.add(handleAuthor);

    boolean present_createDate = true && (isSetCreateDate());
    list.add(present_createDate);
    if (present_createDate)
      list.add(createDate);

    boolean present_remark = true && (isSetRemark());
    list.add(present_remark);
    if (present_remark)
      list.add(remark);

    boolean present_userIds = true && (isSetUserIds());
    list.add(present_userIds);
    if (present_userIds)
      list.add(userIds);

    boolean present_page = true;
    list.add(present_page);
    if (present_page)
      list.add(page);

    boolean present_rows = true;
    list.add(present_rows);
    if (present_rows)
      list.add(rows);

    boolean present_projectId = true;
    list.add(present_projectId);
    if (present_projectId)
      list.add(projectId);

    boolean present_projectName = true && (isSetProjectName());
    list.add(present_projectName);
    if (present_projectName)
      list.add(projectName);

    boolean present_flowName = true && (isSetFlowName());
    list.add(present_flowName);
    if (present_flowName)
      list.add(flowName);

    boolean present_handleAuthorName = true && (isSetHandleAuthorName());
    list.add(present_handleAuthorName);
    if (present_handleAuthorName)
      list.add(handleAuthorName);

    boolean present_handleType = true;
    list.add(present_handleType);
    if (present_handleType)
      list.add(handleType);

    boolean present_flowId = true;
    list.add(present_flowId);
    if (present_flowId)
      list.add(flowId);

    boolean present_handleTypeList = true && (isSetHandleTypeList());
    list.add(present_handleTypeList);
    if (present_handleTypeList)
      list.add(handleTypeList);

    return list.hashCode();
  }

  @Override
  public int compareTo(HandleDifferWarnDTO other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPid()).compareTo(other.isSetPid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pid, other.pid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleDynamicId()).compareTo(other.isSetHandleDynamicId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleDynamicId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleDynamicId, other.handleDynamicId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDiffer()).compareTo(other.isSetDiffer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDiffer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.differ, other.differ);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleDate()).compareTo(other.isSetHandleDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleDate, other.handleDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleAuthor()).compareTo(other.isSetHandleAuthor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleAuthor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleAuthor, other.handleAuthor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateDate()).compareTo(other.isSetCreateDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createDate, other.createDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRemark()).compareTo(other.isSetRemark());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemark()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remark, other.remark);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserIds()).compareTo(other.isSetUserIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userIds, other.userIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPage()).compareTo(other.isSetPage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page, other.page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRows()).compareTo(other.isSetRows());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRows()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rows, other.rows);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProjectId()).compareTo(other.isSetProjectId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProjectId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.projectId, other.projectId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProjectName()).compareTo(other.isSetProjectName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProjectName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.projectName, other.projectName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFlowName()).compareTo(other.isSetFlowName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFlowName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.flowName, other.flowName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleAuthorName()).compareTo(other.isSetHandleAuthorName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleAuthorName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleAuthorName, other.handleAuthorName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleType()).compareTo(other.isSetHandleType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleType, other.handleType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFlowId()).compareTo(other.isSetFlowId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFlowId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.flowId, other.flowId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHandleTypeList()).compareTo(other.isSetHandleTypeList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandleTypeList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handleTypeList, other.handleTypeList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HandleDifferWarnDTO(");
    boolean first = true;

    sb.append("pid:");
    sb.append(this.pid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleDynamicId:");
    sb.append(this.handleDynamicId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("differ:");
    sb.append(this.differ);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleDate:");
    if (this.handleDate == null) {
      sb.append("null");
    } else {
      sb.append(this.handleDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleAuthor:");
    sb.append(this.handleAuthor);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createDate:");
    if (this.createDate == null) {
      sb.append("null");
    } else {
      sb.append(this.createDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("remark:");
    if (this.remark == null) {
      sb.append("null");
    } else {
      sb.append(this.remark);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("userIds:");
    if (this.userIds == null) {
      sb.append("null");
    } else {
      sb.append(this.userIds);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("page:");
    sb.append(this.page);
    first = false;
    if (!first) sb.append(", ");
    sb.append("rows:");
    sb.append(this.rows);
    first = false;
    if (!first) sb.append(", ");
    sb.append("projectId:");
    sb.append(this.projectId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("projectName:");
    if (this.projectName == null) {
      sb.append("null");
    } else {
      sb.append(this.projectName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("flowName:");
    if (this.flowName == null) {
      sb.append("null");
    } else {
      sb.append(this.flowName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleAuthorName:");
    if (this.handleAuthorName == null) {
      sb.append("null");
    } else {
      sb.append(this.handleAuthorName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleType:");
    sb.append(this.handleType);
    first = false;
    if (!first) sb.append(", ");
    sb.append("flowId:");
    sb.append(this.flowId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("handleTypeList:");
    if (this.handleTypeList == null) {
      sb.append("null");
    } else {
      sb.append(this.handleTypeList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HandleDifferWarnDTOStandardSchemeFactory implements SchemeFactory {
    public HandleDifferWarnDTOStandardScheme getScheme() {
      return new HandleDifferWarnDTOStandardScheme();
    }
  }

  private static class HandleDifferWarnDTOStandardScheme extends StandardScheme<HandleDifferWarnDTO> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HandleDifferWarnDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pid = iprot.readI32();
              struct.setPidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HANDLE_DYNAMIC_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.handleDynamicId = iprot.readI32();
              struct.setHandleDynamicIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DIFFER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.differ = iprot.readI32();
              struct.setDifferIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // HANDLE_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.handleDate = iprot.readString();
              struct.setHandleDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // HANDLE_AUTHOR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.handleAuthor = iprot.readI32();
              struct.setHandleAuthorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CREATE_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.createDate = iprot.readString();
              struct.setCreateDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // REMARK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.remark = iprot.readString();
              struct.setRemarkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // USER_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list96 = iprot.readListBegin();
                struct.userIds = new ArrayList<Integer>(_list96.size);
                int _elem97;
                for (int _i98 = 0; _i98 < _list96.size; ++_i98)
                {
                  _elem97 = iprot.readI32();
                  struct.userIds.add(_elem97);
                }
                iprot.readListEnd();
              }
              struct.setUserIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.page = iprot.readI32();
              struct.setPageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // ROWS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.rows = iprot.readI32();
              struct.setRowsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // PROJECT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.projectId = iprot.readI32();
              struct.setProjectIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // PROJECT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.projectName = iprot.readString();
              struct.setProjectNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // FLOW_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.flowName = iprot.readString();
              struct.setFlowNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // HANDLE_AUTHOR_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.handleAuthorName = iprot.readString();
              struct.setHandleAuthorNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // HANDLE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.handleType = iprot.readI32();
              struct.setHandleTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // FLOW_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.flowId = iprot.readI32();
              struct.setFlowIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // HANDLE_TYPE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list99 = iprot.readListBegin();
                struct.handleTypeList = new ArrayList<Integer>(_list99.size);
                int _elem100;
                for (int _i101 = 0; _i101 < _list99.size; ++_i101)
                {
                  _elem100 = iprot.readI32();
                  struct.handleTypeList.add(_elem100);
                }
                iprot.readListEnd();
              }
              struct.setHandleTypeListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HandleDifferWarnDTO struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PID_FIELD_DESC);
      oprot.writeI32(struct.pid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(HANDLE_DYNAMIC_ID_FIELD_DESC);
      oprot.writeI32(struct.handleDynamicId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DIFFER_FIELD_DESC);
      oprot.writeI32(struct.differ);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      if (struct.handleDate != null) {
        oprot.writeFieldBegin(HANDLE_DATE_FIELD_DESC);
        oprot.writeString(struct.handleDate);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HANDLE_AUTHOR_FIELD_DESC);
      oprot.writeI32(struct.handleAuthor);
      oprot.writeFieldEnd();
      if (struct.createDate != null) {
        oprot.writeFieldBegin(CREATE_DATE_FIELD_DESC);
        oprot.writeString(struct.createDate);
        oprot.writeFieldEnd();
      }
      if (struct.remark != null) {
        oprot.writeFieldBegin(REMARK_FIELD_DESC);
        oprot.writeString(struct.remark);
        oprot.writeFieldEnd();
      }
      if (struct.userIds != null) {
        oprot.writeFieldBegin(USER_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.userIds.size()));
          for (int _iter102 : struct.userIds)
          {
            oprot.writeI32(_iter102);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PAGE_FIELD_DESC);
      oprot.writeI32(struct.page);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ROWS_FIELD_DESC);
      oprot.writeI32(struct.rows);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PROJECT_ID_FIELD_DESC);
      oprot.writeI32(struct.projectId);
      oprot.writeFieldEnd();
      if (struct.projectName != null) {
        oprot.writeFieldBegin(PROJECT_NAME_FIELD_DESC);
        oprot.writeString(struct.projectName);
        oprot.writeFieldEnd();
      }
      if (struct.flowName != null) {
        oprot.writeFieldBegin(FLOW_NAME_FIELD_DESC);
        oprot.writeString(struct.flowName);
        oprot.writeFieldEnd();
      }
      if (struct.handleAuthorName != null) {
        oprot.writeFieldBegin(HANDLE_AUTHOR_NAME_FIELD_DESC);
        oprot.writeString(struct.handleAuthorName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HANDLE_TYPE_FIELD_DESC);
      oprot.writeI32(struct.handleType);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(FLOW_ID_FIELD_DESC);
      oprot.writeI32(struct.flowId);
      oprot.writeFieldEnd();
      if (struct.handleTypeList != null) {
        oprot.writeFieldBegin(HANDLE_TYPE_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.handleTypeList.size()));
          for (int _iter103 : struct.handleTypeList)
          {
            oprot.writeI32(_iter103);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HandleDifferWarnDTOTupleSchemeFactory implements SchemeFactory {
    public HandleDifferWarnDTOTupleScheme getScheme() {
      return new HandleDifferWarnDTOTupleScheme();
    }
  }

  private static class HandleDifferWarnDTOTupleScheme extends TupleScheme<HandleDifferWarnDTO> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HandleDifferWarnDTO struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPid()) {
        optionals.set(0);
      }
      if (struct.isSetHandleDynamicId()) {
        optionals.set(1);
      }
      if (struct.isSetDiffer()) {
        optionals.set(2);
      }
      if (struct.isSetStatus()) {
        optionals.set(3);
      }
      if (struct.isSetHandleDate()) {
        optionals.set(4);
      }
      if (struct.isSetHandleAuthor()) {
        optionals.set(5);
      }
      if (struct.isSetCreateDate()) {
        optionals.set(6);
      }
      if (struct.isSetRemark()) {
        optionals.set(7);
      }
      if (struct.isSetUserIds()) {
        optionals.set(8);
      }
      if (struct.isSetPage()) {
        optionals.set(9);
      }
      if (struct.isSetRows()) {
        optionals.set(10);
      }
      if (struct.isSetProjectId()) {
        optionals.set(11);
      }
      if (struct.isSetProjectName()) {
        optionals.set(12);
      }
      if (struct.isSetFlowName()) {
        optionals.set(13);
      }
      if (struct.isSetHandleAuthorName()) {
        optionals.set(14);
      }
      if (struct.isSetHandleType()) {
        optionals.set(15);
      }
      if (struct.isSetFlowId()) {
        optionals.set(16);
      }
      if (struct.isSetHandleTypeList()) {
        optionals.set(17);
      }
      oprot.writeBitSet(optionals, 18);
      if (struct.isSetPid()) {
        oprot.writeI32(struct.pid);
      }
      if (struct.isSetHandleDynamicId()) {
        oprot.writeI32(struct.handleDynamicId);
      }
      if (struct.isSetDiffer()) {
        oprot.writeI32(struct.differ);
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status);
      }
      if (struct.isSetHandleDate()) {
        oprot.writeString(struct.handleDate);
      }
      if (struct.isSetHandleAuthor()) {
        oprot.writeI32(struct.handleAuthor);
      }
      if (struct.isSetCreateDate()) {
        oprot.writeString(struct.createDate);
      }
      if (struct.isSetRemark()) {
        oprot.writeString(struct.remark);
      }
      if (struct.isSetUserIds()) {
        {
          oprot.writeI32(struct.userIds.size());
          for (int _iter104 : struct.userIds)
          {
            oprot.writeI32(_iter104);
          }
        }
      }
      if (struct.isSetPage()) {
        oprot.writeI32(struct.page);
      }
      if (struct.isSetRows()) {
        oprot.writeI32(struct.rows);
      }
      if (struct.isSetProjectId()) {
        oprot.writeI32(struct.projectId);
      }
      if (struct.isSetProjectName()) {
        oprot.writeString(struct.projectName);
      }
      if (struct.isSetFlowName()) {
        oprot.writeString(struct.flowName);
      }
      if (struct.isSetHandleAuthorName()) {
        oprot.writeString(struct.handleAuthorName);
      }
      if (struct.isSetHandleType()) {
        oprot.writeI32(struct.handleType);
      }
      if (struct.isSetFlowId()) {
        oprot.writeI32(struct.flowId);
      }
      if (struct.isSetHandleTypeList()) {
        {
          oprot.writeI32(struct.handleTypeList.size());
          for (int _iter105 : struct.handleTypeList)
          {
            oprot.writeI32(_iter105);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HandleDifferWarnDTO struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(18);
      if (incoming.get(0)) {
        struct.pid = iprot.readI32();
        struct.setPidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.handleDynamicId = iprot.readI32();
        struct.setHandleDynamicIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.differ = iprot.readI32();
        struct.setDifferIsSet(true);
      }
      if (incoming.get(3)) {
        struct.status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(4)) {
        struct.handleDate = iprot.readString();
        struct.setHandleDateIsSet(true);
      }
      if (incoming.get(5)) {
        struct.handleAuthor = iprot.readI32();
        struct.setHandleAuthorIsSet(true);
      }
      if (incoming.get(6)) {
        struct.createDate = iprot.readString();
        struct.setCreateDateIsSet(true);
      }
      if (incoming.get(7)) {
        struct.remark = iprot.readString();
        struct.setRemarkIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TList _list106 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.userIds = new ArrayList<Integer>(_list106.size);
          int _elem107;
          for (int _i108 = 0; _i108 < _list106.size; ++_i108)
          {
            _elem107 = iprot.readI32();
            struct.userIds.add(_elem107);
          }
        }
        struct.setUserIdsIsSet(true);
      }
      if (incoming.get(9)) {
        struct.page = iprot.readI32();
        struct.setPageIsSet(true);
      }
      if (incoming.get(10)) {
        struct.rows = iprot.readI32();
        struct.setRowsIsSet(true);
      }
      if (incoming.get(11)) {
        struct.projectId = iprot.readI32();
        struct.setProjectIdIsSet(true);
      }
      if (incoming.get(12)) {
        struct.projectName = iprot.readString();
        struct.setProjectNameIsSet(true);
      }
      if (incoming.get(13)) {
        struct.flowName = iprot.readString();
        struct.setFlowNameIsSet(true);
      }
      if (incoming.get(14)) {
        struct.handleAuthorName = iprot.readString();
        struct.setHandleAuthorNameIsSet(true);
      }
      if (incoming.get(15)) {
        struct.handleType = iprot.readI32();
        struct.setHandleTypeIsSet(true);
      }
      if (incoming.get(16)) {
        struct.flowId = iprot.readI32();
        struct.setFlowIdIsSet(true);
      }
      if (incoming.get(17)) {
        {
          org.apache.thrift.protocol.TList _list109 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.handleTypeList = new ArrayList<Integer>(_list109.size);
          int _elem110;
          for (int _i111 = 0; _i111 < _list109.size; ++_i111)
          {
            _elem110 = iprot.readI32();
            struct.handleTypeList.add(_elem110);
          }
        }
        struct.setHandleTypeListIsSet(true);
      }
    }
  }

}

