/*变更AOM订单的产品ID*/
DECLARE
  
  CURSOR C_JOB IS
   SELECT A.PID AS PID ,A.PRODUCT_ID,B.PID AS BID,B.PRODUCT_NUM,C.PID AS CID FROM BIZ_PROJECT A 
LEFT JOIN BIZ_PRODUCT B
ON A.PRODUCT_ID = B.PID
LEFT JOIN BIZ_PRODUCT C
ON B.TRADE_TYPE = C.TRADE_TYPE AND C.CITY_ID = 2 AND C.IS_FORECLOSURE IS NULL
WHERE A.PROJECT_TYPE = 6;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
  UPDATE BIZ_PROJECT A SET A.PRODUCT_ID =C_ROW.CID 
  WHERE A.PID = C_ROW.PID AND A.PROJECT_TYPE = 6;
  
  END LOOP;
  commit;
END;
/


DECLARE
 
  CURSOR C_JOB IS
   SELECT ACCT_ID,ORG_ID,USER_ID FROM (
      SELECT A.PID AS ACCT_ID,B.PID AS USER_ID,B.ORG_ID AS ORG_ID FROM CUS_ACCT A LEFT JOIN SYS_USER B
      ON A.PM_USER_ID = B.PID)C
       WHERE C.USER_ID IS NOT NULL;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
  UPDATE CUS_ACCT A SET A.CUS_SOURCE = 0,A.ORG_ID=(SELECT 
        ORG.ID
    FROM 
        SYS_ORG_INFO ORG 
    WHERE ORG.LAYER =2 START WITH ORG.ID = C_ROW.ORG_ID
		 	CONNECT BY PRIOR ORG.PARENT_ID = ORG.ID) WHERE A.PID = C_ROW.ACCT_ID;
  
  END LOOP;
commit;
END;
/

/*物业信息视图*/
CREATE OR REPLACE VIEW V_HOUSE_NAME AS
(SELECT TO_CHAR(WM_CONCAT(A.HOUSE_PROPERTY_CARD)) AS HOUSE_PROPERTY_CARD,
TO_CHAR(WM_CONCAT(A.HOUSE_NAME)) AS HOUSE_NAME,
A.PROJECT_ID FROM BIZ_PROJECT_ESTATE A WHERE A.PROJECT_ID IS NOT NULL AND A.STATUS = 1
GROUP BY A.PROJECT_ID);



