
 /** 赎楼项目信息表增加回款人身份证号,首付款*/
  ALTER TABLE BIZ_PROJECT_FORECLOSURE
		ADD (
		ID_CARD_NUMBER NVARCHAR2(255),
		DOWN_PAYMENT NUMBER(12,2)
		);
	COMMENT ON COLUMN BIZ_PROJECT_FORECLOSURE.ID_CARD_NUMBER IS '回款人身份证号';
	COMMENT ON COLUMN BIZ_PROJECT_FORECLOSURE.DOWN_PAYMENT IS '首付款';
	  
  /*合作城市信息表增加字段*/
  ALTER TABLE ORG_COOPERATE_CITY_INFO
		ADD (
        PROVINCE_CODE NVARCHAR2(255),
         PROVINCE_NAME NVARCHAR2(255),
		CONTACT NVARCHAR2(255),
		PHONE NVARCHAR2(255),
		STATUS INTEGER,
		REMARK NVARCHAR2(255)
		);
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.PROVINCE_CODE IS '省份编码';
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.PROVINCE_NAME IS '省份名字';
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.CONTACT IS '联系人';
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.PHONE IS '联系人电话';
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.STATUS IS '状态';
    COMMENT ON COLUMN ORG_COOPERATE_CITY_INFO.REMARK IS '备注';
	  
/** 一键下载权限*/
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','一键下载权限','一键下载权限','DOWN_LOAD_ALL_DATA',0,1);
	  

-- 初始化合作城市信息表新增字段联系人、电话从机构ORG_ID对应的资产合作机构信息表中
UPDATE (SELECT C.CONTACT,
               C.PHONE,
               A.CONTACT AS ASSETS_CONTACT,
               A.PHONE AS ASSETS_PHONE
          FROM ORG_COOPERATE_CITY_INFO C
         INNER JOIN ORG_ASSETS_COOPERATION_INFO A ON C.ORG_ID = A.PID) U
   SET U.CONTACT = U.ASSETS_CONTACT, U.PHONE = U.ASSETS_PHONE;
   
-- 修正直辖市在机构城市中错误的省级AREA_CODE为对应的市级AREA_CODE
UPDATE ORG_COOPERATE_CITY_INFO
   SET AREA_CODE = '110100'
 WHERE AREA_CODE = '110000'; -- 北京市
UPDATE ORG_COOPERATE_CITY_INFO
   SET AREA_CODE = '120100'
 WHERE AREA_CODE = '120000'; -- 天津市
UPDATE ORG_COOPERATE_CITY_INFO
   SET AREA_CODE = '310100'
 WHERE AREA_CODE = '310000'; -- 上海市
UPDATE ORG_COOPERATE_CITY_INFO
   SET AREA_CODE = '500100'
 WHERE AREA_CODE = '500000'; -- 重庆市

-- 初始化合作城市信息表新增字段省编码、省名称
UPDATE (SELECT C.PROVINCE_CODE, C.PROVINCE_NAME, P.AREA_CODE, P.AREA_NAME
          FROM ORG_COOPERATE_CITY_INFO C
         INNER JOIN SYS_AREA_INFO A ON C.AREA_CODE = A.AREA_CODE
         INNER JOIN SYS_AREA_INFO P ON A.PARENT_CODE = P.AREA_CODE) U
   SET U.PROVINCE_CODE = U.AREA_CODE, U.PROVINCE_NAME = U.AREA_NAME;
	
	/**增加合规复审角色*/
	INSERT INTO SYS_ROLE(PID,ROLE_NAME,ROLE_DESC,ROLE_CODE,STATUS,PARENT_ID) VALUES 
	(SEQ_SYS_ROLE.NEXTVAL, '合规复审', '合规复审人员', 'COMPLIANCE_REVIEW',1,0);
		  
	  