CREATE OR REPLACE VIEW BUSINESS_SOURCE_V AS
(
SELECT F.PID,
     (CASE
       WHEN F.BUSINESS_SOURCE_STR IS NULL THEN
        F.LOOKUP_DESC
       ELSE
        F.LOOKUP_DESC || '--' || F.BUSINESS_SOURCE_STR
     END) AS BUSINESS_SOURCE_STR
FROM (SELECT A.PID,
             (CASE
               WHEN A.BUSINESS_SOURCE = 13782 THEN B.ORG_NAME
               WHEN A.BUSINESS_SOURCE = 13859 THEN A.MY_MAIN
               ELSE
                C.LOOKUP_DESC
             END) AS BUSINESS_SOURCE_STR,
             D.LOOKUP_DESC
        FROM BIZ_PROJECT A, SYS_LOOKUP_VAL D,ORG_ASSETS_COOPERATION_INFO b,SYS_LOOKUP_VAL c
       WHERE A.BUSINESS_SOURCE = D.PID
         and A.BUSINESS_SOURCE_NO = B.PID(+)
         and A.BUSINESS_SOURCE_NO = C.PID(+)
         )F
);


--修改系统原有物业信息的值
DECLARE
  -- LOCAL VARIABLES HERE
  CURSOR C_JOB IS
   SELECT A.PROJECT_ID,
       TO_CHAR(WM_CONCAT(A.HOUSE_NAME)) AS HOUSE_NAME,
       TO_CHAR(WM_CONCAT(A.HOUSE_PROPERTY_CARD)) AS HOUSE_PROPERTY_CARD,
       SUM(A.COST_MONEY) AS COST_MONEY,
       SUM(A.AREA) AS AREA,
       SUM(A.TRANASCTION_MONEY) AS TRANASCTION_MONEY,
       SUM(A.EVALUATION_PRICE) AS EVALUATION_PRICE,
       SUM(A.EVALUATION_NET) AS EVALUATION_NET
  FROM BIZ_PROJECT_ESTATE A
 WHERE A.STATUS = 1 AND A.PROJECT_ID IS NOT NULL GROUP BY A.PROJECT_ID;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
  UPDATE BIZ_PROJECT_PROPERTY SET HOUSE_NAME =C_ROW.HOUSE_NAME,
  HOUSE_PROPERTY_CARD = C_ROW.HOUSE_PROPERTY_CARD,
  COST_MONEY = C_ROW.COST_MONEY,
  AREA = C_ROW.AREA,
  TRANASCTION_MONEY = C_ROW.TRANASCTION_MONEY,
  EVALUATION_PRICE = C_ROW.EVALUATION_PRICE,
  EVALUATION_NET = C_ROW.EVALUATION_NET WHERE PROJECT_ID = C_ROW.PROJECT_ID;
  
  
  END LOOP;
  commit;
END;
/


