--erp系统日志表新增浏览器和ip地址字段
ALTER TABLE SYS_LOG ADD ( 
BROWSER VARCHAR2(255),
IP_ADDRESS VARCHAR2(50)
);
COMMENT ON COLUMN SYS_LOG.BROWSER IS '浏览器';
COMMENT ON COLUMN SYS_LOG.IP_ADDRESS IS 'IP地址';
--aom系统日志表新增浏览器字段
ALTER TABLE ORG_SYS_LOG_INFO ADD ( BROWSER VARCHAR2(255));
COMMENT ON COLUMN ORG_SYS_LOG_INFO.BROWSER IS '浏览器';