

 
/**客户征信报告记录-是否重复查询*/
ALTER TABLE CUS_CREDIT_REPORT_HIS ADD IS_REPEAT  INTEGER;
COMMENT ON COLUMN CUS_CREDIT_REPORT_HIS.IS_REPEAT IS '是否重复查询 （1：是 2：否）';

/**客户征信报告记录-单次价格*/
ALTER TABLE CUS_CREDIT_REPORT_HIS ADD UNIT_PRICE NUMBER(12,2);
COMMENT ON COLUMN CUS_CREDIT_REPORT_HIS.UNIT_PRICE IS '单次价格';

/**客户征信报告记录-是否有人行征信报告  true/false/und*/
ALTER TABLE CUS_CREDIT_REPORT_HIS ADD QUERY_PBOC_STATUS VARCHAR(50);
COMMENT ON COLUMN CUS_CREDIT_REPORT_HIS.QUERY_PBOC_STATUS IS '有无人行征信  true/false/und';




comment on column CUS_CREDIT_REPORT_HIS.DATA_SOURCE is 
'信息来源(1:鹏元征信 2:优分数据 3:FICO大数据评分)';

comment on column CUS_CREDIT_REPORT_HIS.REPORT_TYPE is
'报告类型 1:个人信用报告 2：个人风险汇总 3：个人反欺诈分析 4：刑事案底核查  5：FICO大数据信用评分';


/**征信报告费用配置序列*/
CREATE SEQUENCE SEQ_CREDIT_REPORT_FEE_CONFIG;

/**征信报告费用配置表*/
create table CREDIT_REPORT_FEE_CONFIG 
(
   PID                  INTEGER    PRIMARY KEY,
   DATA_SOURCE          INTEGER,
   REPORT_TYPE          INTEGER,
   UNIT_PRICE           NUMBER(12,2),
   CREATE_TIME          TIMESTAMP(6),
   CREATOR              INTEGER,
   UPDATE_TIME         TIMESTAMP(6),
   UPDATOR              INTEGER,
   REMARK               VARCHAR(2000)
);


comment on table CREDIT_REPORT_FEE_CONFIG is '征信报告费用配置';
comment on column CREDIT_REPORT_FEE_CONFIG.PID is '主键';
comment on column CREDIT_REPORT_FEE_CONFIG.DATA_SOURCE is '信息来源(1:鹏元征信 2:优分数据 3:FICO大数据评分)';
comment on column CREDIT_REPORT_FEE_CONFIG.REPORT_TYPE is '报告类型 1:个人信用报告 2：个人风险汇总 3：个人反欺诈分析 4：刑事案底核查  5：FICO大数据信用评分';
comment on column CREDIT_REPORT_FEE_CONFIG.UNIT_PRICE is '单次价格';
comment on column CREDIT_REPORT_FEE_CONFIG.CREATE_TIME is '创建时间';
comment on column CREDIT_REPORT_FEE_CONFIG.CREATOR is '创建人';
comment on column CREDIT_REPORT_FEE_CONFIG.UPDATE_TIME is '更新时间';
comment on column CREDIT_REPORT_FEE_CONFIG.UPDATOR is '更新人';
comment on column CREDIT_REPORT_FEE_CONFIG.REMARK is '备注';



/**添加权限*/
/** 客户管理>征信报告费用配置管理>新增*/
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','客户管理>征信报告费用配置管理>新增','客户管理>征信报告费用配置管理>新增','CREDIT_REPORT_FEE_CONFIG_ADD',0,1);
/** 客户管理>征信报告费用配置管理>修改*/
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','客户管理>征信报告费用配置管理>修改','客户管理>征信报告费用配置管理>修改','CREDIT_REPORT_FEE_CONFIG_UPDATE',0,1);

/** 客户管理>征信报告费用配置管理>删除*/
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','客户管理>征信报告费用配置管理>删除','客户管理>征信报告费用配置管理>删除','CREDIT_REPORT_FEE_CONFIG_DELETE',0,1);




  
  
  /**更新历史数据，当天只算一条有效记录，更新价格*/
 
   /** 调整 1:个人信用报告*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 2  ,U.UNIT_PRICE = 18  
     WHERE U.PID IN
    (
      SELECT PID FROM (
        SELECT   MIN(C.PID)AS PID, C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE , TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD') AS CREATE_TIME_FORMAT
           FROM  CUS_CREDIT_REPORT_HIS C 
                GROUP BY C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE ,TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD')
      ) OLD
    )   
    AND U.REPORT_TYPE = 1 ;
    
    
   /** 调整 2:个人风险汇总*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 2  ,U.UNIT_PRICE = 0.6  
     WHERE U.PID IN
    (
      SELECT PID FROM (
        SELECT   MIN(C.PID)AS PID, C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE , TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD') AS CREATE_TIME_FORMAT
           FROM  CUS_CREDIT_REPORT_HIS C 
                GROUP BY C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE ,TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD')
      ) OLD
    )   
    AND U.REPORT_TYPE = 2 ;
    
   /** 调整 3:个人反欺诈分析*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 2  ,U.UNIT_PRICE = 5  
     WHERE U.PID IN
    (
      SELECT PID FROM (
        SELECT   MIN(C.PID)AS PID, C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE , TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD') AS CREATE_TIME_FORMAT
           FROM  CUS_CREDIT_REPORT_HIS C 
                GROUP BY C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE ,TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD')
      ) OLD
    )   
    AND U.REPORT_TYPE = 3 ;
    
   /** 调整 4:刑事案底核查*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 2  ,U.UNIT_PRICE = 2  
     WHERE U.PID IN
    (
      SELECT PID FROM (
        SELECT   MIN(C.PID)AS PID, C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE , TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD') AS CREATE_TIME_FORMAT
           FROM  CUS_CREDIT_REPORT_HIS C 
                GROUP BY C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE ,TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD')
      ) OLD
    )   
    AND U.REPORT_TYPE = 4 ;
    
    
   /** 调整 5:FICO大数据信用评分*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 2  ,U.UNIT_PRICE = 4  
     WHERE U.PID IN
    (
      SELECT PID FROM (
        SELECT   MIN(C.PID)AS PID, C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE , TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD') AS CREATE_TIME_FORMAT
           FROM  CUS_CREDIT_REPORT_HIS C 
                GROUP BY C.QUERY_NAME ,C.REPORT_TYPE ,C.QUERY_DOCUMENT_NO,
                 C.QUERY_PHONE ,TO_CHAR(C.CREATE_TIME,'YYYY-MM-DD')
      ) OLD
    )   
    AND U.REPORT_TYPE = 5 ;
    
    
    
   /** 调整价格*/
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 1  ,U.UNIT_PRICE = 18
           WHERE U.REPORT_TYPE = 1  AND ( U.IS_REPEAT != 2 OR IS_REPEAT IS NULL OR IS_REPEAT ='') ;
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 1  ,U.UNIT_PRICE = 0.6  
           WHERE U.REPORT_TYPE = 2 AND ( U.IS_REPEAT != 2 OR IS_REPEAT IS NULL OR IS_REPEAT ='') ;
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 1  ,U.UNIT_PRICE = 5 
           WHERE U.REPORT_TYPE = 3 AND ( U.IS_REPEAT != 2 OR IS_REPEAT IS NULL OR IS_REPEAT ='') ;
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 1  ,U.UNIT_PRICE = 2 
           WHERE U.REPORT_TYPE = 4 AND ( U.IS_REPEAT != 2 OR IS_REPEAT IS NULL OR IS_REPEAT ='' ) ;
   UPDATE  CUS_CREDIT_REPORT_HIS U SET   U.IS_REPEAT = 1  ,U.UNIT_PRICE = 4
           WHERE U.REPORT_TYPE = 5 AND ( U.IS_REPEAT != 2 OR IS_REPEAT IS NULL OR IS_REPEAT ='' ) ;
    
    
             
        


 
 