COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.REC_PRO
  IS '收款项目:咨询费=1,手续费=2,第一次放款=3,一次赎楼余额转二次放款=4,第二次放款=5,监管（客户）资金转入=6,佣金=7,展期费=8,二次放款=9,下户费=10,居间服务费=11';
  
UPDATE BIZ_LOAN_COLLECT_FEE_HIS T SET T.REC_PRO=1;

ALTER TABLE BIZ_LOAN_FINANCE_HANDLE
ADD (
  COLLECT_FEE_STATUS       INTEGER  DEFAULT 1
);
COMMENT ON COLUMN ORG_COOPERAT_COMPANY_APPLY_INF.ASSURE_MONEY_PROPORTION
  IS '收费状态：未收费=1，已收费=2';  

CREATE TABLE BIZ_LOAN_BATCH_REFUND_FEE_MAIN
(
   PID           INTEGER PRIMARY KEY,
   BATCH_NAME    VARCHAR2(255) UNIQUE,
   APPLY_STATUS  INTEGER,
   CREATE_DATE          TIMESTAMP,
   CREATER_ID           INTEGER,
   UPDATE_ID            INTEGER,
   UPDATE_DATE          TIMESTAMP
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_LOAN_BATCH_REFUND_FEE_MAIN
  IS '批量退费主表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_LOAN_BATCH_REFUND_FEE_MAIN.PID
  IS '主键';
COMMENT ON COLUMN BIZ_LOAN_BATCH_REFUND_FEE_MAIN.BATCH_NAME
  IS '批量名';
COMMENT ON COLUMN BIZ_LOAN_BATCH_REFUND_FEE_MAIN.APPLY_STATUS
  IS '申请状态：未申请=1，申请中=2，驳回=3，审核中=4，审核通过=5，审核不通过=6，已归档=7';



CREATE TABLE BIZ_BATCH_REFUND_FEE_RELATION
(
   PID           INTEGER PRIMARY KEY,
   BATCH_REFUND_FEE_MAIN_ID    INTEGER,
   PROJECT_ID    INTEGER,
   REFUND_FEE_ID   INTEGER
);

COMMENT ON TABLE BIZ_BATCH_REFUND_FEE_RELATION
  IS '批量退费关联表';

COMMENT ON COLUMN BIZ_BATCH_REFUND_FEE_RELATION.PID
  IS '主键';
COMMENT ON COLUMN BIZ_BATCH_REFUND_FEE_RELATION.PROJECT_ID
  IS '批量退费主表id';
COMMENT ON COLUMN BIZ_BATCH_REFUND_FEE_RELATION.PROJECT_ID
  IS '项目id';
COMMENT ON COLUMN BIZ_BATCH_REFUND_FEE_RELATION.REFUND_FEE_ID
  IS '退费id';

create sequence SEQ_BATCH_REFUND_FEE_MAIN;
create sequence SEQ_BATCH_REFUND_FEE_RELATION;

DECLARE
  CURSOR C_JOB IS
   SELECT * FROM BIZ_LOAN_FINANCE_HANDLE T WHERE T.STATUS>=2;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  UPDATE BIZ_LOAN_FINANCE_HANDLE T SET T.COLLECT_FEE_STATUS=1;
  FOR C_ROW IN C_JOB LOOP
    UPDATE BIZ_LOAN_FINANCE_HANDLE T SET T.COLLECT_FEE_STATUS=2 WHERE T.PID=C_ROW.PID;
  END LOOP;

END;
/

INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '房抵贷放款按钮权限',
   '房抵贷放款按钮权限',
   'FINANCE_FDD_MAKE_LOANS',
   0,
   1);
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '房抵贷入库登记按钮权限',
   '房抵贷入库登记按钮权限',
   'FDD_AFTERLOAN_REGISTER',
   0,
   1);
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '房抵贷出库申请按钮权限',
   '房抵贷出库申请按钮权限',
   'FDD_AFTERLOAN_OUTPUT',
   0,
   1);
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '房抵贷出具注销材料按钮权限',
   '房抵贷出具注销材料按钮权限',
   'FDD_AFTERLOAN_CANCLE_FILE',
   0,
   1);
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '房抵贷退证登记按钮权限',
   '房抵贷退证登记按钮权限',
   'FDD_AFTERLOAN_RETURN_REGISTER',
   0,
   1);
   commit;