 /**
  * 删除流程中间表中重复的数据
  */    
 DELETE FROM BIZ_WORKFLOW_PROJECT WHERE PID IN(     
 SELECT B.PID
   FROM BIZ_WORKFLOW_PROJECT B,
        (SELECT A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY, COUNT(*)
           FROM BIZ_WORKFLOW_PROJECT A
          GROUP BY A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY
         HAVING COUNT(*) > 1) A
  WHERE A.PROJECT_ID = B.PROJECT_ID
    AND A.PROCESS_DEFINITION_KEY = B.PROCESS_DEFINITION_KEY
    AND A.REF_ID = B.REF_ID
    AND B.PID NOT IN
        (SELECT MAX(A.PID)
           FROM BIZ_WORKFLOW_PROJECT A
          GROUP BY A.PROJECT_ID, A.REF_ID, A.PROCESS_DEFINITION_KEY
         HAVING COUNT(*) > 1));
commit;
/
/**
 * 变更流程中间表里的唯一性限制
 */
         alter table BIZ_WORKFLOW_PROJECT drop constraint UNIQUE_BIZ_WORKFLOW_PROJECT; 
alter table BIZ_WORKFLOW_PROJECT
  ADD constraint UNIQUE_WORKFLOW_PROJECT unique (REF_ID, PROCESS_DEFINITION_KEY,PROJECT_ID);