-- 查档历史表
CREATE TABLE BIZ_CHECK_DOCUMENT_HIS
(
  PID              INTEGER PRIMARY KEY,
  PROJECT_ID       INTEGER NOT NULL,
  HOUSE_ID       INTEGER NOT NULL,
  CHECK_STATUS     INTEGER DEFAULT 1,
  APPROVAL_STATUS  INTEGER DEFAULT 1,
  CHECK_DATE       TIMESTAMP(6),
  CHECK_WAY        INTEGER,
  REMARK           VARCHAR2(2048),
  ATTACHMENT_ID    INTEGER,
  CREATER_DATE     TIMESTAMP(6),
  CREATER_ID       INTEGER,
  UPDATE_ID        INTEGER,
  UPDATE_DATE      TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_CHECK_DOCUMENT_HIS
  IS '查档历史表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.PID
  IS '主键';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.HOUSE_ID
  IS '物业ID';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.CHECK_STATUS
  IS '查档状态：未查档=1,抵押=2,有效=3,无效=4,查封=5,抵押查封=6,轮候查封=7';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.APPROVAL_STATUS
  IS '审批状态：未审批=1,不通过=2,通过=3,重新查档=4';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.CHECK_DATE
  IS '查档时间';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.CHECK_WAY
  IS '查档方式：1=人工查询,2=系统查询';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.REMARK
  IS '审批意见';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.ATTACHMENT_ID
  IS '附件ID';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_CHECK_DOCUMENT_HIS.UPDATE_DATE
  IS '更新时间';

CREATE SEQUENCE SEQ_CHECK_DOCUMENT_HIS;
  
-- 差诉讼历史表
CREATE TABLE BIZ_CHECK_LITIGATION_HIS
(
  PID             INTEGER PRIMARY KEY,
  PROJECT_ID      INTEGER NOT NULL,
  CHECK_STATUS    INTEGER DEFAULT 1,
  APPROVAL_STATUS INTEGER DEFAULT 1,
  CHECK_DATE      TIMESTAMP(6),
  CHECK_WAY        INTEGER,
  REMARK          VARCHAR2(2048),
  ATTACHMENT_ID   INTEGER,
  CREATER_DATE    TIMESTAMP(6),
  CREATER_ID      INTEGER,
  UPDATE_ID       INTEGER,
  UPDATE_DATE     TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_CHECK_LITIGATION_HIS
  IS '差诉讼历史表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.PID
  IS '主键';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.CHECK_STATUS
  IS '诉讼状态：未查诉讼=1,无新增诉讼=2,有增诉讼=3,有新增诉讼非本人=4';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.APPROVAL_STATUS
  IS '审批状态：未审批=1,不通过=2,通过=3,重新查诉讼=4';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.CHECK_DATE
  IS '查法院网时间';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.CHECK_WAY
  IS '查诉讼方式：1=人工查询,2=系统查询';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.REMARK
  IS '审批意见';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.ATTACHMENT_ID
  IS '附件ID';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_CHECK_LITIGATION_HIS.UPDATE_DATE
  IS '更新时间';
CREATE SEQUENCE SEQ_CHECK_LITIGATION_HIS;  

-- 贷后异常上报表
CREATE TABLE BIZ_AFTER_EXCEPTION_REPORT
(
  PID             		INTEGER PRIMARY KEY,
  PROJECT_ID      		INTEGER NOT NULL,
  MONITOR_USER_ID       INTEGER NOT NULL,
  EXCEPTION_TYPE   		INTEGER DEFAULT 1,
  STATUS           		INTEGER DEFAULT 1,
  MONITOR_DATE      	TIMESTAMP(6),
  NOTICE_WAY     		VARCHAR2(25),
  REMARK         		NVARCHAR2(1000),
  ATTACHMENT_ID   		INTEGER,
  CREATER_DATE    		TIMESTAMP(6),
  CREATER_ID      		INTEGER,
  UPDATE_ID       		INTEGER,
  UPDATE_DATE     		TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_AFTER_EXCEPTION_REPORT
  IS '贷后异常上报表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.PID
  IS '主键';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.MONITOR_USER_ID
  IS '监控人';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.EXCEPTION_TYPE
  IS '异常类型：1=展期，2=逾期，3=房产查封，4=新增诉讼，100=其他';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.STATUS
  IS '状态';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.MONITOR_DATE
  IS '监控时间';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.NOTICE_WAY
  IS '通知方式（多个以英文逗号隔开）：1=短信，2=邮件';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.REMARK
  IS '备注';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_AFTER_EXCEPTION_REPORT.UPDATE_DATE
  IS '更新时间';
CREATE SEQUENCE SEQ_AFTER_EXCEPTION_REPORT;    
  


-- 机构合作信息修改申请表
CREATE TABLE ORG_COOPERATION_UPDATE_APPLY
(
  PID                           INTEGER PRIMARY KEY,
  ORG_ID                        INTEGER NOT NULL,
  CREDIT_LIMIT                  NUMBER(12,2),
  OLD_CREDIT_LIMIT                  NUMBER(12,2),
  ACTIVATE_CREDIT_LIMIT         NUMBER(12,2),
  OLD_ACTIVATE_CREDIT_LIMIT         NUMBER(12,2),
  PLAN_RATE                     NUMBER(12,2),
  OLD_PLAN_RATE                     NUMBER(12,2),
  FUND_SIZE_MONEY               NUMBER(12,2),
  OLD_FUND_SIZE_MONEY               NUMBER(12,2),
  ASSURE_MONEY_PROPORTION       NUMBER(12,2),
  OLD_ASSURE_MONEY_PROPORTION       NUMBER(12,2),
  ASSURE_MONEY                  NUMBER(12,2),
  OLD_ASSURE_MONEY                  NUMBER(12,2),
  ACTUAL_FEE_RATE               NUMBER(12,2),
  OLD_ACTUAL_FEE_RATE               NUMBER(12,2),
  SINGLE_UPPER_LIMIT            NUMBER(12,2),
  OLD_SINGLE_UPPER_LIMIT            NUMBER(12,2),
  ASSURE_MONEY_REMARK           NVARCHAR2(2000),
  OLD_ASSURE_MONEY_REMARK           NVARCHAR2(2000),
  APPLY_STATUS                  INTEGER DEFAULT 1,
  REMARK                        NVARCHAR2(2000),
  CREATER_DATE                  TIMESTAMP(6),
  CREATER_ID                    INTEGER,
  UPDATE_ID                     INTEGER,
  UPDATE_DATE                   TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ORG_COOPERATION_UPDATE_APPLY
  IS '机构合作信息修改表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.PID
  IS '主键';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ORG_ID
  IS '机构id';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.CREDIT_LIMIT
  IS '授信额度';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_CREDIT_LIMIT
  IS '旧授信额度';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ACTIVATE_CREDIT_LIMIT
  IS '启用授信额度';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_ACTIVATE_CREDIT_LIMIT
  IS '旧启用授信额度';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.PLAN_RATE
  IS '预收费费率';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_PLAN_RATE
  IS '旧预收费费率';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.FUND_SIZE_MONEY
  IS '出款标准';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_FUND_SIZE_MONEY
  IS '旧出款标准';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ASSURE_MONEY_PROPORTION
  IS '保证金比例';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_ASSURE_MONEY_PROPORTION
  IS '旧保证金比例';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ASSURE_MONEY
  IS '保证金';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_ASSURE_MONEY
  IS '旧保证金';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ACTUAL_FEE_RATE
  IS '实际收费费率';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_ACTUAL_FEE_RATE
  IS '旧实际收费费率';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.SINGLE_UPPER_LIMIT
  IS '单笔上限';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_SINGLE_UPPER_LIMIT
  IS '旧单笔上限';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.ASSURE_MONEY_REMARK
  IS '保证金备注';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.OLD_ASSURE_MONEY_REMARK
  IS '旧保证金备注';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.APPLY_STATUS
  IS '申请状态：未申请=1,申请中=2,驳回=3,审核中=4,审核通过=5,审核不通过=6,已归档=7';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.REMARK
  IS '备注';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN ORG_COOPERATION_UPDATE_APPLY.UPDATE_DATE
  IS '更新时间';
CREATE SEQUENCE SEQ_COOPERATION_UPDATE_APPLY;

-- 异常业务监控表
CREATE TABLE BIZ_EXCEPTION_MONITOR
(
  PID                  	INTEGER NOT NULL,
  EXCEPTION_ID          INTEGER,
  PROJECT_ID            INTEGER,
  MONITOR_DATE         	TIMESTAMP(6),
  MONITOR_TITLE        	NVARCHAR2(2000),
  MONITOR_CONTENT      	NVARCHAR2(2000),
  MONITOR_RESULT      	NVARCHAR2(2000),
  MONITOR_OPINION     	NVARCHAR2(2000),
  DANGER_LEVEL			INTEGER DEFAULT 1,
  FOLLOW_STATUS        	INTEGER DEFAULT 1,
  NEXT_MONITOR_DATE   	TIMESTAMP(6),
  NEXT_FOLLOW_ID       	INTEGER,
  FOLLOW_ID            	INTEGER,
  NOTICE_WAY         	VARCHAR2(55),
  STATUS              	INTEGER DEFAULT 1,
  CREATER_DATE        	TIMESTAMP(6),
  CREATER_ID          	INTEGER,
  UPDATE_ID          	INTEGER,
  UPDATE_DATE         	TIMESTAMP(6),
  REMARK               	NVARCHAR2(2000)
);
/* Add comments to the table */
comment on table BIZ_EXCEPTION_MONITOR
  is '异常业务监控表';
-- Add comments to the columns 
comment on column BIZ_EXCEPTION_MONITOR.PID
  is '主键';
comment on column BIZ_EXCEPTION_MONITOR.EXCEPTION_ID
  is '异常业务ID';
  comment on column BIZ_EXCEPTION_MONITOR.PROJECT_ID
  is '项目ID';
comment on column BIZ_EXCEPTION_MONITOR.MONITOR_DATE
  is '监控时间';
comment on column BIZ_EXCEPTION_MONITOR.MONITOR_TITLE
  is '监控标题';
comment on column BIZ_EXCEPTION_MONITOR.MONITOR_CONTENT
  is '监控内容';
comment on column BIZ_EXCEPTION_MONITOR.MONITOR_RESULT
  is '监控结果';
comment on column BIZ_EXCEPTION_MONITOR.MONITOR_OPINION
  is '监控意见';
  COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.DANGER_LEVEL
  IS '风险等级:正常状态=1,正常风险=2,重大风险=3,紧急风险=4';
comment on column BIZ_EXCEPTION_MONITOR.FOLLOW_STATUS
  is '跟进状态：是=1；否=2';
comment on column BIZ_EXCEPTION_MONITOR.NEXT_MONITOR_DATE
  is '下次监控时间';
comment on column BIZ_EXCEPTION_MONITOR.NEXT_FOLLOW_ID
  IS '下次跟进人ID';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.FOLLOW_ID
  IS '跟进人ID';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.NOTICE_WAY
  IS '监控提醒方式：短信=1，邮件=2，系统=3';
  COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.STATUS
  IS '状态';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.UPDATE_DATE
  IS '更新时间';
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.REMARK
  IS '备注';
  CREATE SEQUENCE SEQ_EXCEPTION_MONITOR;
  
/*申请报告表*/
CREATE TABLE BIZ_APPLY_REPORT
(
  PID                 		INTEGER NOT NULL,
  EXCEPTION_ID          	INTEGER,
  PROJECT_ID                INTEGER,
  USER_ID        		    INTEGER,
  REPORT_DATE         		TIMESTAMP(6),
  UN_ASSURE_CONDITION      	NVARCHAR2(2000),
  HOUSE_PROPERY_CONDITION   NVARCHAR2(2000),
  REMARK               		NVARCHAR2(2000),
  CREATE_DATE   			TIMESTAMP(6),
  CREATE_ID     		 	INTEGER,
  UPDATE_ID       			INTEGER,
  UPDATE_DATE     			TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_APPLY_REPORT
  IS '贷后申请报告表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_APPLY_REPORT.PID
  IS '主键';
COMMENT ON COLUMN BIZ_APPLY_REPORT.EXCEPTION_ID
  IS '异常业务ID';
COMMENT ON COLUMN BIZ_APPLY_REPORT.USER_ID
  IS '报告人ID';
COMMENT ON COLUMN BIZ_APPLY_REPORT.REPORT_DATE
  IS '报告时间';
COMMENT ON COLUMN BIZ_APPLY_REPORT.UN_ASSURE_CONDITION
  IS '反担保情况';
COMMENT ON COLUMN BIZ_APPLY_REPORT.HOUSE_PROPERY_CONDITION
  IS '房产情况';
COMMENT ON COLUMN BIZ_APPLY_REPORT.REMARK
  IS '备注';
COMMENT ON COLUMN BIZ_APPLY_REPORT.CREATE_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_APPLY_REPORT.CREATE_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_APPLY_REPORT.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_APPLY_REPORT.UPDATE_DATE
  IS '更新时间';
 CREATE SEQUENCE SEQ_APPLY_REPORT;

/*贷后诉讼表*/
CREATE TABLE BIZ_AFTER_LOAN_LEGAL
(
  PID           	INTEGER NOT NULL,
  REPORT_ID    	 	INTEGER,
  STATUS        	INTEGER DEFAULT 1,
  LEGAL_CONTENT 	NVARCHAR2(2000),
  REMARK        	NVARCHAR2(2000),
  CREATER_DATE    	TIMESTAMP(6),
  CREATER_ID      	INTEGER,
  UPDATE_ID       	INTEGER,
  UPDATE_DATE     	TIMESTAMP(6)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_AFTER_LOAN_LEGAL
  IS '贷后诉讼表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.PID
  IS '主键';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.REPORT_ID
  IS '关联申请报告表ID';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.STATUS
  IS '诉讼状态：个人诉讼=1,企业诉讼=2';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.LEGAL_CONTENT
  IS '诉讼内容';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.REMARK
  IS '备注';
  COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.CREATER_ID
  IS '创建人ID';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.UPDATE_ID
  IS '更新人ID';
COMMENT ON COLUMN BIZ_AFTER_LOAN_LEGAL.UPDATE_DATE
  IS '更新时间';
   CREATE SEQUENCE SEQ_AFTER_LOAN_LEGAL;

  
--项目表增加 赎楼贷后监控状态
ALTER TABLE biz_project
ADD (
 fore_after_monitor_status  INTEGER default 1
);
COMMENT ON COLUMN biz_project.fore_after_monitor_status
  IS '赎楼贷后监控状态：无异常=1，有异常=2';
  --异常监控表增加跟进人姓名
  ALTER TABLE BIZ_EXCEPTION_MONITOR
	ADD (
	 		follow_name NVARCHAR2(200)
	);
COMMENT ON COLUMN BIZ_EXCEPTION_MONITOR.follow_name
  IS '跟进人姓名';
  
/*项目表增加申请报告字段*/
ALTER TABLE biz_project
ADD (
 fore_after_report_status  INTEGER default 1
);
COMMENT ON COLUMN biz_project.fore_after_report_status
  IS '赎楼贷后申请报告字段：新增=1，修改=2';
  
  
  
--短信表
CREATE TABLE SYS_SMS_INFO 
(
   PID                   NUMBER               NOT NULL,
   TELPHONE             VARCHAR(20)          NOT NULL,
   CONTENT               NVARCHAR2(2000)       ,
   SEND_DATE            TIMESTAMP,
   CREATE_DATE          TIMESTAMP            NOT NULL,
   CREATOR_ID           NUMBER,
   CATEGORY             NUMBER,
   STATUS               NUMBER               DEFAULT 1 NOT NULL,
   IP_ADDRESS               VARCHAR(55),
   CONSTRAINT "PK_SYS_SMS_INFO" PRIMARY KEY (PID)
);
COMMENT ON TABLE SYS_SMS_INFO IS
'短信信息表';
COMMENT ON COLUMN SYS_SMS_INFO.PID IS
'主键';
COMMENT ON COLUMN SYS_SMS_INFO.TELPHONE IS
'手机号码';
COMMENT ON COLUMN SYS_SMS_INFO.CONTENT IS
'短信内容';
COMMENT ON COLUMN SYS_SMS_INFO.SEND_DATE IS
'发送时间';
COMMENT ON COLUMN SYS_SMS_INFO.CREATE_DATE IS
'创建时间';
COMMENT ON COLUMN SYS_SMS_INFO.CREATOR_ID IS
'创建者ID';
COMMENT ON COLUMN SYS_SMS_INFO.CATEGORY IS
'类型';
COMMENT ON COLUMN SYS_SMS_INFO.STATUS IS
'状态：1表示有效,2表示失效';
COMMENT ON COLUMN SYS_SMS_INFO.IP_ADDRESS IS
'IP地址';
CREATE SEQUENCE SEQ_SYS_SMS_INFO;

--邮件表
CREATE TABLE SYS_MAIL_INFO 
(
   PID                   NUMBER       PRIMARY KEY,
   SUBJECT                NVARCHAR2(2000),
   CONTENT               NVARCHAR2(2000)       ,
   SEND_MAIL             VARCHAR2(255),
   REC_MAIL           VARCHAR2(255),
   CREATOR_ID           NUMBER,
   CREATOR_DATE          TIMESTAMP,
   CATEGORY           NUMBER,
   STATUS           NUMBER,
   IP_ADDRESS           VARCHAR2(55)
);
COMMENT ON TABLE SYS_MAIL_INFO IS
'邮件信息表';
COMMENT ON COLUMN SYS_MAIL_INFO.PID IS
'主键';
COMMENT ON COLUMN SYS_MAIL_INFO.subject IS
'主题';
COMMENT ON COLUMN SYS_MAIL_INFO.CONTENT IS
'内容';
COMMENT ON COLUMN SYS_MAIL_INFO.SEND_MAIL IS
'发送邮件';
COMMENT ON COLUMN SYS_MAIL_INFO.REC_MAIL IS
'接受邮箱';
COMMENT ON COLUMN SYS_MAIL_INFO.CREATOR_ID IS
'创建者ID';
COMMENT ON COLUMN SYS_MAIL_INFO.CREATOR_DATE IS
'创建时间';
COMMENT ON COLUMN SYS_MAIL_INFO.CATEGORY IS
'类型';
COMMENT ON COLUMN SYS_MAIL_INFO.STATUS IS
'状态：1表示发送成功,2表示发送失败';
COMMENT ON COLUMN SYS_MAIL_INFO.IP_ADDRESS IS
'IP地址';
CREATE SEQUENCE SEQ_SYS_MAIL_INFO;


--DROP TABLE BIZ_CHECK_DOCUMENT_HIS;
--DROP TABLE BIZ_CHECK_LITIGATION_HIS;
--DROP TABLE BIZ_AFTER_EXCEPTION_REPORT;
--DROP TABLE ORG_COOPERATION_UPDATE_APPLY;
--DROP TABLE BIZ_EXCEPTION_MONITOR;
--DROP TABLE BIZ_APPLY_REPORT;
--DROP TABLE BIZ_AFTER_LOAN_LEGAL;
--DROP TABLE SYS_SMS_INFO;
--DROP TABLE SYS_MAIL_INFO;
--
--DROP SEQUENCE SEQ_CHECK_DOCUMENT_HIS;
--DROP SEQUENCE SEQ_CHECK_LITIGATION_HIS;
--DROP SEQUENCE SEQ_AFTER_EXCEPTION_REPORT;
--DROP SEQUENCE SEQ_COOPERATION_UPDATE_APPLY;
--DROP SEQUENCE SEQ_SYS_SMS_INFO;
--DROP SEQUENCE SEQ_SYS_MAIL_INFO;
