--add new code 贷后统计--
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14103,'SLDYWTJ',1,'赎楼贷业务统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '赎楼贷业务统计报表', 'xlsx', 12, 1, '', SYSDATE, 1);

INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14119,'SLDHZYWTJ',1,'赎楼贷合作机构业务统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '赎楼贷合作机构业务统计', 'xlsx', 12, 1, '', SYSDATE, 1);

INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14122,'CWTJBB',1,'财务统计报表导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '财务统计报表', 'xlsx', 12, 1, '', SYSDATE, 1);

INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14123,'TZXFTJ',1,'退咨询费统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '退咨询费统计', 'xlsx', 12, 1, '', SYSDATE, 1);

INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14221,'ZJYWTJL',1,'资金业务量统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '资金业务量统计', 'xlsx', 12, 1, '', SYSDATE, 1);
--新增详情列表
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14223,'XZXQMB',1,'新增详情统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '新增详情统计', 'xlsx', 12, 1, '', SYSDATE, 1);

--结清详情列表
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,14224,'JQXQMB',1,'结清详情统计导出模版',SYSDATE);

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '结清详情统计', 'xlsx', 12, 1, '', SYSDATE, 1);

--业务审批明细列表
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values (SEQ_SYS_LOOKUP_VAL.NEXTVAL,14227,'YWSPMXTJ',1,'业务审批明细统计导出模版',SYSDATE) ;

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '业务审批明细统计', 'xlsx', 12, 1, '', SYSDATE, 1);

--业务审批台账列表
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values (SEQ_SYS_LOOKUP_VAL.NEXTVAL,14229,'YWSPTZTJ',1,'业务审批台账统计导出模版',SYSDATE) ;

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '业务审批台账统计', 'xlsx', 12, 1, '', SYSDATE, 1);


--业务审批台账明细列表
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values (SEQ_SYS_LOOKUP_VAL.NEXTVAL,14231,'YWSPTZMX',1,'业务审批台账明细导出模版',SYSDATE) ;

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '业务审批台账明细统计', 'xlsx', 12, 1, '', SYSDATE, 1);

CREATE FUNCTION GET_WK(P_DATE IN DATE)
 RETURN VARCHAR2
 IS
  V_WK VARCHAR2(30);
  V_N NUMBER;
BEGIN
  SELECT TO_NUMBER(TO_CHAR(P_DATE, 'D'))
    INTO V_N
    FROM DUAL;
  IF V_N = 1 
   THEN 
    V_WK :=
     TO_CHAR(P_DATE - 6, 'YYYY/MM/DD')           
            || '-'          
            || TO_CHAR(P_DATE, 'YYYY/MM/DD');  
  ELSE  
    V_WK :=
     TO_CHAR(P_DATE + (7 - (5 + V_N)), 'YYYY/MM/DD')
           
            || '-'
           
            || TO_CHAR(P_DATE + (7 - (5 + V_N)) + 6, 'YYYY/MM/DD');
  
  END IF;
  RETURN V_WK;
END;
/
