COMMENT ON COLUMN BIZ_PROJECT.COLLECT_FILE_STATUS
  IS '收件状态,未收件=1,已收件=2';    
  
ALTER TABLE ORG_COOPERAT_COMPANY_APPLY_INF
ADD (
  ASSURE_MONEY_PROPORTION       NUMBER(12,2),
  ACTIVATE_CREDIT_LIMIT         NUMBER(12,2),
  ASSURE_MONEY_REMARK           NVARCHAR2(2000)
);
COMMENT ON COLUMN ORG_COOPERAT_COMPANY_APPLY_INF.ASSURE_MONEY_PROPORTION
  IS '保证金比例';  
COMMENT ON COLUMN ORG_COOPERAT_COMPANY_APPLY_INF.ACTIVATE_CREDIT_LIMIT
  IS '启用授信额度';  
COMMENT ON COLUMN ORG_COOPERAT_COMPANY_APPLY_INF.ASSURE_MONEY_REMARK
  IS '保证金备注';  
  

--初始化旧数据的保证金比例：（保证金/授信额度）*100=保证金比例
UPDATE ORG_COOPERAT_COMPANY_APPLY_INF T SET T.ASSURE_MONEY_PROPORTION=(T.ASSURE_MONEY/T.CREDIT_LIMIT)*100 WHERE T.ASSURE_MONEY>0;
--初始化旧数据的启用授信额度：实收保证金/(保证金比例/100)=启用授信额度
UPDATE ORG_COOPERAT_COMPANY_APPLY_INF T SET T.ACTIVATE_CREDIT_LIMIT=T.REAL_ASSURE_MONEY/(T.ASSURE_MONEY_PROPORTION/100) WHERE T.ASSURE_MONEY_PROPORTION>0;
  

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','添加添加保证金流水记录求情权限','添加添加保证金流水记录求情权限','orgAssureFundRecordController/add',0,1);

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','查看修改合作信息权限','查看修改合作信息权限','SHOW_ORG_COOPERATE',0,1);
 
  INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','查看在途业务监控信息权限','查看在途业务监控信息权限','TO_TRANSIT_MONITOR_SHOW',0,1);  
--日志表增加字符长度  
ALTER TABLE SYS_LOG MODIFY ( LOG_MSG NVARCHAR2(2000));  
  --财务放款资金来源 
 CREATE OR REPLACE VIEW FINANCE_MAKE_LOANS_RES_V AS(
SELECT (CASE
         WHEN (AFH.PRO_RESOURCE_MONEY > 0 AND AFH.PRO_RESOURCE_MONEY_2 > 0) THEN
          CO1.ORG_NAME || ',' || CO2.ORG_NAME
         WHEN AFH.PRO_RESOURCE_MONEY > 0 THEN
          CO1.ORG_NAME
         WHEN AFH.PRO_RESOURCE_MONEY_2 > 0 THEN
          CO2.ORG_NAME
       END) AS PRO_RESOURCE,
       FH.PROJECT_ID
  FROM BIZ_LOAN_FINANCE_HANDLE FH
  LEFT JOIN BIZ_LOAN_APPLY_FINANCE_HANDLE AFH
    ON FH.PID = AFH.FINANCE_HANDLE_ID
  LEFT JOIN CAPITAL_ORG_INFO CO1
    ON CO1.ORG_CODE = AFH.PRO_RESOURCE
  LEFT JOIN CAPITAL_ORG_INFO CO2
    ON CO2.ORG_CODE = AFH.PRO_RESOURCE_2
 WHERE AFH.REC_PRO = 3
);

  
  CREATE OR REPLACE FUNCTION LAST_COOPERATION_APLLY_STATUS(IN_ORG_ID IN INT)
  RETURN NUMBER IS
  COOPERATION_UPDATE_STATUS NUMBER;
BEGIN 
 SELECT A.APPLY_STATUS INTO COOPERATION_UPDATE_STATUS
           FROM (SELECT OCUA.APPLY_STATUS
                                    FROM ORG_COOPERATION_UPDATE_APPLY OCUA
                                   WHERE OCUA.ORG_ID = IN_ORG_ID
                                   ORDER BY OCUA.CREATER_DATE DESC) a
                           WHERE ROWNUM = 1;
  RETURN(COOPERATION_UPDATE_STATUS);
END LAST_COOPERATION_APLLY_STATUS;
/


-- 把就得查档记录复制到新增的查档历史记录表中
DECLARE
  CURSOR C_JOB IS
    SELECT C.PROJECT_ID,
           PE.PID AS HOUSE_ID,
           C.CHECK_STATUS,
           C.APPROVAL_STATUS,
           C.CHECK_DATE,
           C.REMARK,
           C.ATTACHMENT_ID,
           C.CREATER_DATE,
           C.CREATER_ID,
           C.UPDATE_ID,
           C.UPDATE_DATE
      FROM BIZ_CHECK_DOCUMENT C
      LEFT JOIN BIZ_PROJECT_ESTATE PE
        ON C.PROJECT_ID = PE.PROJECT_ID
        WHERE C.CHECK_DATE IS NOT NULL;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
    INSERT INTO BIZ_CHECK_DOCUMENT_HIS
      (PID,
       PROJECT_ID,
       HOUSE_ID,
       CHECK_STATUS,
       APPROVAL_STATUS,
       CHECK_DATE,
       CHECK_WAY,
       REMARK,
       ATTACHMENT_ID,
       CREATER_DATE,
       CREATER_ID,
       UPDATE_ID,
       UPDATE_DATE)
    VALUES
      (SEQ_CHECK_DOCUMENT_HIS.NEXTVAL,
       C_ROW.PROJECT_ID,
       C_ROW.HOUSE_ID,
       C_ROW.CHECK_STATUS,
       C_ROW.APPROVAL_STATUS,
       C_ROW.CHECK_DATE,
       1,
        C_ROW.REMARK,
       C_ROW.ATTACHMENT_ID,
       C_ROW.CREATER_DATE,
       C_ROW.CREATER_ID,
       C_ROW.UPDATE_ID,
        C_ROW.UPDATE_DATE);
  END LOOP;

END;
/
