

/*变更万通的客户经理*/
UPDATE BIZ_PROJECT T SET T.PM_USER_ID = 20379 WHERE T.PID = 14262;

 /**更新点融返回错误信息*/
 UPDATE BIZ_PROJECT_PARTNER SET LOAN_ID = 11756861 , REQUEST_STATUS= 2 , APPROVAL_STATUS = 1,
        REQUEST_TIME = SYSDATE , SUBMIT_APPROVAL_TIME = SYSDATE
    WHERE PID = 1082 ;

/*机构表添加录单员ID*/
ALTER TABLE BIZ_PROJECT ADD ( RECORD_CLERK_ID INTEGER);
COMMENT ON COLUMN BIZ_PROJECT.RECORD_CLERK_ID IS
'录单员';
/*物业添加评估净值总价*/
ALTER TABLE BIZ_PROJECT_PROPERTY ADD ( EVALUATION_NET NUMBER);
COMMENT ON COLUMN BIZ_PROJECT_PROPERTY.EVALUATION_NET IS
'评估净值总价';

/*机构表添加拒单类型*/
ALTER TABLE BIZ_PROJECT ADD ( REJECT_TYPE INTEGER);
COMMENT ON COLUMN BIZ_PROJECT.REJECT_TYPE IS
'拒单类型1、黑名单2、其他原因';

COMMENT ON COLUMN BIZ_PROJECT.IS_REJECT IS
'是否驳回1、完全驳回2、正常3、补充资料4、拒单';
comment on column BIZ_PROJECT.REQUEST_STATUS is
'业务申请状态（合作机构web端展示）1、未提交2、待审核3、审核中4、审核通过5、审核失败';
comment on column BIZ_PROJECT.STATUS is
'1、有效2、无效';

/*修改ERP后端提交的业务分配状态为已分配*/
UPDATE BIZ_PROJECT A SET A.IS_ASSIGNED = 2 WHERE A.PROJECT_TYPE =2;
ALTER TABLE BIZ_PROJECT MODIFY IS_ASSIGNED DEFAULT 2;

/*修改物业名称、房产证号的长度*/
ALTER TABLE BIZ_PROJECT_PROPERTY MODIFY ( HOUSE_NAME NVARCHAR2(2000));
ALTER TABLE BIZ_PROJECT_PROPERTY MODIFY ( HOUSE_PROPERTY_CARD NVARCHAR2(2000));

/*物业信息转移*/
DECLARE
  CURSOR C_JOB IS
    SELECT BP.PROJECT_ID,
           BP.HOUSE_NAME,
           BP.AREA,
           BP.HOUSE_PROPERTY_CARD,
           BP.EVALUATION_PRICE,
           BP.COST_MONEY,
           BP.TRANASCTION_MONEY,
           BP.PURPOSE
      FROM BIZ_PROJECT_PROPERTY BP;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
    INSERT INTO BIZ_PROJECT_ESTATE
      (PID,
       PROJECT_ID,
       HOUSE_NAME,
       COST_MONEY,
       AREA,
       HOUSE_PROPERTY_CARD,
       PURPOSE,
       TRANASCTION_MONEY,
       EVALUATION_PRICE,
       STATUS)
    VALUES
      (SEQ_BIZ_PROJECT_ESTATE.NEXTVAL,
       C_ROW.PROJECT_ID,
       C_ROW.HOUSE_NAME,
       C_ROW.COST_MONEY,
       C_ROW.AREA,
       C_ROW.HOUSE_PROPERTY_CARD,
       C_ROW.PURPOSE,
       C_ROW.TRANASCTION_MONEY,
       C_ROW.EVALUATION_PRICE,
       1);
  END LOOP;

END;
/


/*创建物业地址信息视图*/
CREATE OR REPLACE VIEW V_HOUSE_ADDRESS AS (SELECT A.PID,(SELECT B.AREA_NAME FROM SYS_AREA_INFO B WHERE B.AREA_CODE = A.HOUSE_PROVINCE_CODE) ||
  (SELECT C.AREA_NAME FROM SYS_AREA_INFO C WHERE C.AREA_CODE = A.HOUSE_CITY_CODE) ||
  (SELECT D.AREA_NAME FROM SYS_AREA_INFO D WHERE D.AREA_CODE = A.HOUSE_DISTRICT_CODE) AS HOUSE_ADDRESS
  FROM BIZ_PROJECT_ESTATE A);
  
  /*创建修改贷前数据按钮权限*/
  INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','贷款信息变更','贷款信息变更','CHANGE_PROJECT_INFO',0,1);
  
  /*创建拒单按钮权限*/
  INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','拒单','拒单','REFUSE_PROJECT',0,1);
/*修改机构产品名称*/
UPDATE BIZ_PRODUCT A SET A.PRODUCT_NAME='非交易现金赎楼' WHERE A.PID = 101;
UPDATE BIZ_PRODUCT A SET A.PRODUCT_NAME='交易现金赎楼' WHERE A.PID = 102;

/*原贷款银行数据转移*/
DECLARE
  CURSOR C_JOB IS
    SELECT BF.PROJECT_ID,
       BF.OLD_LOAN_BANK,
       BF.OLD_LOAN_PERSON,
       BF.OLD_LOAN_MONEY,
       BF.OLD_LOAN_PHONE,
       BF.OLD_OWED_AMOUNT,
       BF.OLD_LOAN_TIME,
       BF.OLD_LOAN_BANK_BRANCH,PS.PID AS ESTATE_ID
  FROM BIZ_PROJECT_FORECLOSURE BF,BIZ_PROJECT_ESTATE PS WHERE BF.PROJECT_ID = PS.PROJECT_ID;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
    INSERT INTO BIZ_ORIGINAL_LOAN
  (PID,
   PROJECT_ID,
   OLD_LOAN_BANK,
   OLD_LOAN_BANK_BRANCH,
   OLD_LOAN_MONEY,
   OLD_OWED_AMOUNT,
   OLD_LOAN_TIME,
   OLD_LOAN_PERSON,
   OLD_LOAN_PHONE,STATUS,ESTATE_ID)
values
  (SEQ_BIZ_ORIGINAL_LOAN.NEXTVAL,
       C_ROW.PROJECT_ID,
       C_ROW.OLD_LOAN_BANK,
       C_ROW.OLD_LOAN_BANK_BRANCH,
       C_ROW.OLD_LOAN_MONEY,
       C_ROW.OLD_OWED_AMOUNT,
       C_ROW.OLD_LOAN_TIME,
       C_ROW.OLD_LOAN_PERSON,
       C_ROW.OLD_LOAN_PHONE,
       1,
       C_ROW.ESTATE_ID);
  END LOOP;

END;
/

/*修改小科以前的数据，将录单员设为客户经理*/
DECLARE
  CURSOR C_JOB IS
 SELECT A.PID, A.PM_USER_ID, A.RECORD_CLERK_ID, S.REAL_NAME
   FROM BIZ_PROJECT A, SYS_USER S
  WHERE A.PROJECT_TYPE = 2
    AND A.RECORD_CLERK_ID IS NULL
    AND A.PROJECT_SOURCE = 2
    AND A.PM_USER_ID = S.PID;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
    UPDATE BIZ_PROJECT A
       SET A.RECORD_CLERK_ID = C_ROW.PM_USER_ID,
           A.DECLARATION = C_ROW.REAL_NAME
     WHERE A.PID = C_ROW.PID;
  END LOOP;

END;
/

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','合作机构息费结算历史数据','合作机构息费结算历史数据','CREATE_HISTORY_FEE_SETTLE',0,1); 
 
