--问题反馈
CREATE TABLE SYS_PROBLEM_FEEDBACK
(
   PID                 INTEGER PRIMARY KEY,
   FEEDBACK_CONTENT    VARCHAR2(2048),
   PROBLEM_source      INTEGER,
   CREATER_DATE        TIMESTAMP,
   CREATER_ID          INTEGER
);
COMMENT ON TABLE SYS_PROBLEM_FEEDBACK IS
'问题反馈';
COMMENT ON COLUMN SYS_PROBLEM_FEEDBACK.PID
  IS 'ID';
COMMENT ON COLUMN SYS_PROBLEM_FEEDBACK.FEEDBACK_CONTENT
  IS '反馈内容';
COMMENT ON COLUMN SYS_PROBLEM_FEEDBACK.PROBLEM_source
  IS '问题来源：PC=1,安卓=2,IOS=3';
COMMENT ON COLUMN SYS_PROBLEM_FEEDBACK.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN SYS_PROBLEM_FEEDBACK.CREATER_ID
  IS '创建者';
  
CREATE SEQUENCE SEQ_PROBLEM_FEEDBACK;


-- APP版本信息（版本升级）
CREATE TABLE SYS_APP_VERSION_INFO
(
  PID                 INTEGER PRIMARY KEY,
  APP_NAME            VARCHAR2(255),
  APP_DESCRIPTION            VARCHAR2(2048),
  APP_VERSION             VARCHAR2(20),
  STATUS              INTEGER,
  FILE_ID              INTEGER,
  SYSTEM_PLATFORM      INTEGER,
  DOWNLOAN_COUNT       INTEGER,
  COERCIVENESS_UPGRADES_STATUS       INTEGER,
  APP_CATEGORY       INTEGER,
  CREATER_DATE       TIMESTAMP,
  CREATER_ID       INTEGER,
  UPDATE_ID        INTEGER,
  UPDATE_DATE      TIMESTAMP
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE SYS_APP_VERSION_INFO
  IS 'APP版本信息（版本升级）';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN SYS_APP_VERSION_INFO.APP_NAME
  IS 'app名称';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.APP_DESCRIPTION
  IS '描述';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.APP_VERSION
  IS '版本号';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.STATUS
  IS '状态：1=有效，-1=无效';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.SYSTEM_PLATFORM
  IS '系统类型：1=Android，2=IOS';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.FILE_ID
  IS '文件ID';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.DOWNLOAN_COUNT
  IS '下载次数';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.COERCIVENESS_UPGRADES_STATUS
  IS '强制升级状态：1=不强制升级，2强制升级';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.APP_CATEGORY
  IS 'APP类型：1=erp系统';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.CREATER_DATE
  IS '创建时间';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.CREATER_ID
  IS '创建者';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.UPDATE_ID
  IS '更新者';
COMMENT ON COLUMN SYS_APP_VERSION_INFO.UPDATE_DATE
  IS '更新时间';
  

CREATE SEQUENCE SEQ_SYS_APP_VERSION_INFO;
