--修改系统原有数据来源的值
declare
  -- Local variables here
  cursor c_job is
   SELECT C.*,D.PID,D.ORG_NAME from 
   (SELECT A.PID AS PROJECT_ID,A.BUSINESS_SOURCE_NO,B.LOOKUP_VAL 
   FROM BIZ_PROJECT A,SYS_LOOKUP_VAL B WHERE A.BUSINESS_SOURCE = 13782 
AND A.BUSINESS_SOURCE_NO = B.PID) C,ORG_ASSETS_COOPERATION_INFO D 
where D.ORG_NAME  like '%'||C.LOOKUP_VAL ||'%';
  c_row c_job%rowtype;
begin
  for c_row in c_job loop
  UPDATE BIZ_PROJECT A SET A.BUSINESS_SOURCE_NO = C_ROW.PID WHERE A.PID = C_ROW.PROJECT_ID AND A.BUSINESS_SOURCE_NO = C_ROW.BUSINESS_SOURCE_NO;
  
  end loop;
	commit;
end;
/

--创建业务来源视图，列为业务ID以及业务来源字段
CREATE OR REPLACE VIEW BUSINESS_SOURCE_V AS(
SELECT F.PID,(CASE WHEN F.BUSINESS_SOURCE_STR IS NULL THEN F.LOOKUP_DESC ELSE F.LOOKUP_DESC ||'--'|| F.BUSINESS_SOURCE_STR END) AS BUSINESS_SOURCE_STR
FROM (SELECT A.PID,(CASE WHEN A.BUSINESS_SOURCE = 13782 THEN
(SELECT B.ORG_NAME FROM ORG_ASSETS_COOPERATION_INFO B WHERE A.BUSINESS_SOURCE_NO = B.PID)
WHEN A.BUSINESS_SOURCE = 13859 THEN A.MY_MAIN
ELSE
(SELECT C.LOOKUP_DESC FROM SYS_LOOKUP_VAL C WHERE A.BUSINESS_SOURCE_NO = C.PID) END ) AS BUSINESS_SOURCE_STR,D.LOOKUP_DESC
FROM BIZ_PROJECT A,SYS_LOOKUP_VAL D WHERE A.BUSINESS_SOURCE = D.PID) F 
);

--修改机构提单的业务来源数据
UPDATE BIZ_PROJECT A SET A.BUSINESS_SOURCE = 13782,A.BUSINESS_SOURCE_NO = A.ORG_ID WHERE A.PROJECT_TYPE = 6;