create table BIZ_PROJECT_RETREAT
(
  PID             NUMBER NOT NULL,
  OLD_PROJECT_ID  NUMBER,
  NEW_PROJECT_ID  NUMBER,
  RETREAT_USER_ID NUMBER,
  RETREAT_TIME    TIMESTAMP(6),
  constraint PK_BIZ_PROJECT_RETREAT primary key (PID)
);
CREATE SEQUENCE SEQ_BIZ_PROJECT_RETREAT;
comment on column BIZ_PROJECT_RETREAT.PID
  is '主键';
comment on column BIZ_PROJECT_RETREAT.OLD_PROJECT_ID
  is '旧业务ID';
comment on column BIZ_PROJECT_RETREAT.NEW_PROJECT_ID
  is '新业务ID';
comment on column BIZ_PROJECT_RETREAT.RETREAT_USER_ID
  is '回撤人ID';
comment on column BIZ_PROJECT_RETREAT.RETREAT_TIME
  is '回撤时间';
  
  
 --万通推送业务添加的字段
alter table BIZ_PROJECT add ( IS_NEED_FINANCIAL INTEGER DEFAULT 1);
comment on column BIZ_PROJECT.IS_NEED_FINANCIAL is
'是否需要小科资金 1不需要2需要（万通推单新增字段）';

--万通推送按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','万通推送按钮权限','万通推送按钮权限','UPDATE_FINANCIAL',0,1); 
--运营经理撤单按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','运营经理撤单','运营经理撤单','PROJECT_CHECHAN_BUSINESS',0,1);

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','启用撤单业务','启用撤单业务','RETREAT_PROJECT_INFO',0,1);
