ALTER TABLE BIZ_PROJECT MODIFY ( AUDITOR_OPINION NVARCHAR2(2000));
ALTER TABLE BIZ_PROJECT MODIFY ( CHECHAN_CAUSE NVARCHAR2(2000));
ALTER TABLE BIZ_PROJECT MODIFY ( SURVEY_RESULT NVARCHAR2(2000));

ALTER TABLE BIZ_LOAN_APPLY_FINANCE_HANDLE MODIFY ( FUND_MANAGER_REMARK NVARCHAR2(2000));
ALTER TABLE BIZ_LOAN_APPLY_FINANCE_HANDLE MODIFY ( FINANCE_DIRECTOR_REMARK NVARCHAR2(2000));
--修改默认值
ALTER TABLE BIZ_PROJECT MODIFY INNER_OR_OUT DEFAULT 2;