CREATE OR REPLACE TRIGGER TRIG_CUS_PERSON
  BEFORE INSERT ON CUS_PERSON
  FOR EACH ROW
DECLARE
  V_COUNT NUMBER;
BEGIN
  IF :NEW.RELATION_TYPE = 2 THEN 
    
  SELECT COUNT(*) INTO V_COUNT FROM CUS_PERSON WHERE ACCT_ID = :NEW.ACCT_ID AND RELATION_TYPE = :NEW.RELATION_TYPE;
  IF V_COUNT>0 THEN
  RAISE_APPLICATION_ERROR(-20600,'配偶信息只能存在一个');
  END IF;
END IF;
END TRIG_CUS_PERSON;
/


INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改机构合作信息（系统）','修改机构合作信息（系统）','EDIT_ORG_COOPERATE',0,1); 
 
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改合伙人合作信息（系统）','修改合伙人合作信息（系统）','EDIT_PARTNER_COOPERATE',0,1); 
 
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改业务申请信息（系统）','修改业务申请信息（系统）','EDIT_BIZ_PROJECT',0,1); 
 