--UPDATE SYS_ROLE T
--   SET T.ROLE_CODE = 'OPERATE_DEPARTMENT'
-- WHERE T.ROLE_CODE = 'RISK_SPECIALIST'
--   AND T.PID = '10020';
   
   
--查档文件文件
CREATE TABLE BIZ_LOAN_CHECK_DOCUMENT_FILE
(
  PID                        INTEGER PRIMARY KEY,
  FILE_CATEGORY                 INTEGER,
  PROJECT_ID                 INTEGER,
  FILE_ID                    INTEGER
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BIZ_LOAN_CHECK_DOCUMENT_FILE
  IS '查档文件关联';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BIZ_LOAN_CHECK_DOCUMENT_FILE.PID
  IS '主键';
COMMENT ON COLUMN BIZ_LOAN_CHECK_DOCUMENT_FILE.FILE_CATEGORY
  IS '文件类型：查档=1，查档复合=2';
COMMENT ON COLUMN BIZ_LOAN_CHECK_DOCUMENT_FILE.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_LOAN_CHECK_DOCUMENT_FILE.FILE_ID
  IS '文件ID';
  
CREATE SEQUENCE SEQ_CHECK_DOCUMENT_FILE;

--添加临时字段
ALTER TABLE BIZ_DYNAMIC 
ADD (
  DYNAMIC_NUMBER_TEMP  VARCHAR2(55),
  MODUEL_NUMBER_TEMP   VARCHAR2(55)
);

--复制值到临时字段
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='a' WHERE T.DYNAMIC_NUMBER=10;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='b' WHERE T.DYNAMIC_NUMBER=20;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='c' WHERE T.DYNAMIC_NUMBER=30;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='d' WHERE T.DYNAMIC_NUMBER=40;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='e' WHERE T.DYNAMIC_NUMBER=50;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='f' WHERE T.DYNAMIC_NUMBER=60;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='g' WHERE T.DYNAMIC_NUMBER=70;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='g_a' WHERE T.DYNAMIC_NUMBER=71;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='g_b' WHERE T.DYNAMIC_NUMBER=72;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='h' WHERE T.DYNAMIC_NUMBER=80;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='i' WHERE T.DYNAMIC_NUMBER=90;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='j' WHERE T.DYNAMIC_NUMBER=100;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='k' WHERE T.DYNAMIC_NUMBER=110;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='l' WHERE T.DYNAMIC_NUMBER=120;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='m' WHERE T.DYNAMIC_NUMBER=130;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='n' WHERE T.DYNAMIC_NUMBER=140;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='o' WHERE T.DYNAMIC_NUMBER=150;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='p' WHERE T.DYNAMIC_NUMBER=160;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='q' WHERE T.DYNAMIC_NUMBER=170;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='r' WHERE T.DYNAMIC_NUMBER=180;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='s' WHERE T.DYNAMIC_NUMBER=190;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='t' WHERE T.DYNAMIC_NUMBER=200;
UPDATE BIZ_DYNAMIC T SET T.DYNAMIC_NUMBER_TEMP='u' WHERE T.DYNAMIC_NUMBER=210;

UPDATE BIZ_DYNAMIC T SET T.MODUEL_NUMBER_TEMP='a' WHERE T.MODUEL_NUMBER=1;
UPDATE BIZ_DYNAMIC T SET T.MODUEL_NUMBER_TEMP='b' WHERE T.MODUEL_NUMBER=2;
--删除旧的字段
ALTER TABLE BIZ_DYNAMIC DROP COLUMN DYNAMIC_NUMBER;
ALTER TABLE BIZ_DYNAMIC DROP COLUMN MODUEL_NUMBER;
--修改临时字段名称
ALTER TABLE BIZ_DYNAMIC RENAME COLUMN DYNAMIC_NUMBER_TEMP TO DYNAMIC_NUMBER;
ALTER TABLE BIZ_DYNAMIC RENAME COLUMN MODUEL_NUMBER_TEMP TO MODUEL_NUMBER;
ALTER TABLE BIZ_DYNAMIC MODIFY PARENT_DYNAMIC_NUMBER VARCHAR2(55);
COMMENT ON COLUMN BIZ_DYNAMIC.DYNAMIC_NUMBER IS '动态编号';
COMMENT ON COLUMN BIZ_DYNAMIC.MODUEL_NUMBER IS '模块编号';

--

ALTER TABLE BIZ_LOAN_REFUND_FEE MODIFY REC_ACCOUNT VARCHAR2(255);
ALTER TABLE BIZ_LOAN_REFUND_FEE MODIFY REC_ACCOUNT_NAME VARCHAR2(255);

ALTER TABLE BIZ_INTERMEDIATE_TRANSFER MODIFY REC_ACCOUNT VARCHAR2(255);
ALTER TABLE BIZ_INTERMEDIATE_TRANSFER MODIFY TRANSFER_ACCOUNT VARCHAR2(255);
ALTER TABLE BIZ_INTERMEDIATE_TRANSFER MODIFY REC_ACCOUNT_NAME VARCHAR2(255);
ALTER TABLE BIZ_INTERMEDIATE_TRANSFER MODIFY TRANSFER_ACCOUNT_NAME VARCHAR2(255);
--申请业务处理信息
ALTER TABLE BIZ_LOAN_APPLY_HANDLE_INFO MODIFY CONTACT_PERSON VARCHAR2(255);

--机构管理平台--用户表
ALTER TABLE ORG_USER_INFO MODIFY NICK_NAME VARCHAR2(100);
ALTER TABLE ORG_USER_INFO MODIFY DEPT_NAME VARCHAR2(100);
ALTER TABLE ORG_USER_INFO MODIFY JOB_NO VARCHAR2(100);
--机构管理平台--用户表
ALTER TABLE ORG_ASSETS_COOPERATION_INFO MODIFY CONTACT VARCHAR2(100);

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','赎楼驳回按钮','赎楼驳回按钮','FORECLOSURE_TURN_DOWN',0,1);
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','赎楼按钮','赎楼按钮','FORECLOSURE',0,1);

