ALTER TABLE BIZ_PROJECT_FILE ADD CREATE_NODE  INTEGER;
COMMENT ON COLUMN BIZ_PROJECT_FILE.CREATE_NODE is '文件上传节点';

COMMENT ON COLUMN BIZ_PROJECT_GUARANTEE.GUARANTEE_FEE is '咨询费';

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','贷前文件新增权限','贷前文件新增权限','UPLOAD_PROJECT_FILE',0,1);
--流程关联表添加唯一性约束
ALTER TABLE BIZ_WORKFLOW_PROJECT
  ADD CONSTRAINT UNIQUE_BIZ_WORKFLOW_PROJECT
  UNIQUE (REF_ID,WORKFLOW_INSTANCE_ID);
  

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改项目名称','修改项目名称','UPDATE_PROJECT_NAME',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','撤销推送小科','撤销推送小科','CANCLE_FINANCIAL',0,1);
  
  /*项目放款视图，查询结果为项目ID，放款总金额，放款来源，放款来源金额*/
  CREATE OR REPLACE VIEW V_PROJECT_LOAN AS
(
	SELECT PID,PROJECT_ID,REC_DATE,PRO_RESOURCE,REC_MONEY,PRO_RESOURE_MONEY
  FROM (SELECT FH.PID,
               FH.PROJECT_ID,
               AFH.REC_DATE,
               AFH.PRO_RESOURCE,
               AFH.REC_MONEY,
               AFH.REC_MONEY AS PRO_RESOURE_MONEY
          FROM BIZ_LOAN_FINANCE_HANDLE FH
          LEFT JOIN BIZ_LOAN_APPLY_FINANCE_HANDLE AFH
            ON FH.PID = AFH.FINANCE_HANDLE_ID
         WHERE AFH.REC_PRO = 3
           AND FH.STATUS = 3
           AND AFH.PRO_RESOURCE_MONEY_2 IS NULL
        UNION ALL
        SELECT FH.PID,
               FH.PROJECT_ID,
               AFH.REC_DATE,
               AFH.PRO_RESOURCE_2 AS PRO_RESOURCE,
               AFH.REC_MONEY,
               AFH.PRO_RESOURCE_MONEY_2 AS PRO_RESOURCE_MONEY
          FROM BIZ_LOAN_FINANCE_HANDLE FH
          LEFT JOIN BIZ_LOAN_APPLY_FINANCE_HANDLE AFH
            ON FH.PID = AFH.FINANCE_HANDLE_ID
         WHERE AFH.REC_PRO = 3
           AND FH.STATUS = 3
           AND AFH.PRO_RESOURCE_MONEY_2 > 0
           AND AFH.PRO_RESOURCE_MONEY IS NULL
        UNION ALL
        SELECT * FROM
        (SELECT A.PID,
               A.PROJECT_ID,
               B.REC_DATE,
               PRO_RESOURCE,
               B.REC_MONEY,
               B.PRO_RESOURCE_MONEY
          FROM BIZ_LOAN_FINANCE_HANDLE A, BIZ_LOAN_APPLY_FINANCE_HANDLE B
         WHERE A.PID = B.FINANCE_HANDLE_ID
           AND B.REC_PRO = 3
           AND A.STATUS = 3
           AND PRO_RESOURCE_MONEY IS NOT NULL
           AND PRO_RESOURCE_MONEY_2 IS NOT NULL
        UNION ALL
        SELECT A.PID,
               A.PROJECT_ID,
               B.REC_DATE,
               PRO_RESOURCE_2,
               B.REC_MONEY,
               B.PRO_RESOURCE_MONEY_2
          FROM BIZ_LOAN_FINANCE_HANDLE A, BIZ_LOAN_APPLY_FINANCE_HANDLE B
         WHERE A.PID = B.FINANCE_HANDLE_ID
           AND B.REC_PRO = 3
           AND A.STATUS = 3
           AND PRO_RESOURCE_MONEY IS NOT NULL
           AND PRO_RESOURCE_MONEY_2 IS NOT NULL
         ORDER BY 1,2) A) WHERE PRO_RESOURE_MONEY >0);