

/**合作机构附件表添加合作机构项目ID*/
ALTER TABLE BIZ_PROJECT_PARTNER_FILE ADD PARTNER_ID  INTEGER;
COMMENT ON COLUMN BIZ_PROJECT_PARTNER_FILE.PARTNER_ID IS '合作机构项目ID';


/**调整历史字段，只适合历史版本 项目一对一关系*/
UPDATE BIZ_PROJECT_PARTNER_FILE F SET F.PARTNER_ID = (
       SELECT PID FROM BIZ_PROJECT_PARTNER P WHERE F.PROJECT_ID = P.PROJECT_ID
);

/**修改备注------------------------------------*/
/**申请状态状态*/
COMMENT ON COLUMN BIZ_PROJECT_PARTNER.REQUEST_STATUS IS '1：未申请 2：申请成功/已申请  3：申请中   4：申请拒绝';

/**是否关闭  */
COMMENT ON COLUMN BIZ_PROJECT_PARTNER.IS_CLOSED IS '关闭状态 (1：未关闭 2：已关闭)';


/**放款状态*/
COMMENT ON COLUMN BIZ_PROJECT_PARTNER.LOAN_STATUS IS '放款状态(1：未申请 2：申请中3：放款中 4：放款成功 5：放款失败 6：驳回)';

/**还款、回购状态*/
COMMENT ON COLUMN BIZ_PROJECT_PARTNER.REPAYMENT_REPURCHASE_STATUS IS '还款、回购状态(1:未申请2:已申请3:确认收到；4：未收到; 5：确认中; 6：己逾期  ; 7：坏帐; 8：正常; 9：宽限期内)';

/**当前操作人*/
COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PM_USER_ID IS '当前操作人';


/**预警处理：处理类型*/
COMMENT ON COLUMN BIZ_LOAN_HANDLE_DIFFER_WARN.HANDLE_TYPE IS '处理类型：客户经理处理数据=1,其他=2 ，系统查档=3';
/**历史预警处理：处理类型*/
COMMENT ON COLUMN BIZ_HIS_HANDLE_DIFFER_WARN.HANDLE_TYPE IS '处理类型：客户经理处理数据=1,其他=2 ，系统查档=3';


 --删除预警列表外键
 ALTER TABLE BIZ_LOAN_HANDLE_DIFFER_WARN 
  DROP  CONSTRAINT FK_HDW_HD_PID ;
 --删除历史预警列表外键
 ALTER TABLE BIZ_HIS_HANDLE_DIFFER_WARN 
  DROP  CONSTRAINT FK_HHW_HD_PID ;

-- 修改动态办理ID可为空 
ALTER TABLE BIZ_LOAN_HANDLE_DIFFER_WARN MODIFY HANDLE_DYNAMIC_ID NULL;
-- 修改动态办理ID可为空
ALTER TABLE BIZ_HIS_HANDLE_DIFFER_WARN MODIFY HANDLE_DYNAMIC_ID NULL;

