   --收费历史表
CREATE TABLE BIZ_LOAN_COLLECT_FEE_HIS
(
   PID                 INTEGER PRIMARY KEY,
   FINANCE_HANDLE_ID   INTEGER,
   PROJECT_ID          INTEGER,
   CONSULTING_FEE      NUMBER(12,2),
   POUNDAGE            NUMBER(12,2),
   BROKERAGE           NUMBER(12,2),
   REC_DATE            TIMESTAMP,
   PRO_RESOURCE        VARCHAR2(255),
   REC_ACCOUNT          VARCHAR2(255),
   CREATER_ID          INTEGER,
   CREATER_DATE        TIMESTAMP
);
COMMENT ON TABLE BIZ_LOAN_COLLECT_FEE_HIS
  IS '收费历史表';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.PID
  IS 'ID';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.FINANCE_HANDLE_ID
  IS '财务办理ID';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.CONSULTING_FEE
  IS '咨询费';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.POUNDAGE
  IS '手续费';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.BROKERAGE
  IS '佣金';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.REC_DATE
  IS '收费日期';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.REC_DATE
  IS '款项来源';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.REC_DATE
  IS '收费账号';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.CREATER_ID
  IS '操作人';
COMMENT ON COLUMN BIZ_LOAN_COLLECT_FEE_HIS.CREATER_DATE
  IS '操作日期';
CREATE SEQUENCE SEQ_COLLECT_FEE_HIS;

   --放款延期记录
CREATE TABLE BIZ_LOAN_SUSPEND_RECORD
(
   PID                 INTEGER PRIMARY KEY,
   PROJECT_ID          INTEGER,
   START_DATE        TIMESTAMP,
   END_DATE        TIMESTAMP,
   SUSPEND_DAY          INTEGER,
   REMARK              NVARCHAR2(500),
   CREATER_ID          INTEGER,
   CREATER_DATE        TIMESTAMP
);
COMMENT ON TABLE BIZ_LOAN_SUSPEND_RECORD
  IS '放款延期记录';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.PID
  IS 'ID';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.PROJECT_ID
  IS '项目ID';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.START_DATE
  IS '开始日期';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.END_DATE
  IS '结束日期';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.SUSPEND_DAY
  IS '挂起天数';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.REMARK
  IS '备注';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.CREATER_ID
  IS '操作人';
COMMENT ON COLUMN BIZ_LOAN_SUSPEND_RECORD.CREATER_DATE
  IS '操作日期';
CREATE SEQUENCE SEQ_LOANS_SUSPEND_RECORD;


-- 按钮权限
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '期限顺延按钮权限',
   '期限顺延按钮权限',
   'LOAN_SUSPEND_BTN',
   0,
   1); 

-- 把旧收费记录复制到新增的收费历史记录表中
DECLARE
  CURSOR C_JOB IS
    SELECT A.PROJECT_ID,B.FINANCE_HANDLE_ID, B.CONSULTING_FEE,B.POUNDAGE,B.BROKERAGE,B.REC_ACCOUNT,B.REC_DATE,B.PRO_RESOURCE,B.CREATER_ID,B.CREATER_DATE
  FROM BIZ_LOAN_FINANCE_HANDLE A
  INNER JOIN (SELECT B.FINANCE_HANDLE_ID,
                    SUM(CASE WHEN REC_PRO =1 THEN B.REC_MONEY ELSE 0 END) AS CONSULTING_FEE,
                    SUM(CASE WHEN REC_PRO =2 THEN B.REC_MONEY ELSE 0 END) AS POUNDAGE,
                    SUM(CASE WHEN REC_PRO =7 THEN B.REC_MONEY ELSE 0 END) AS BROKERAGE,
                    MAX(CASE WHEN REC_PRO =1 THEN B.REC_ACCOUNT ELSE '' END) AS REC_ACCOUNT,
                    MAX(CASE WHEN REC_PRO =1 THEN B.REC_DATE ELSE NULL END) AS REC_DATE,
                    MAX(CASE WHEN REC_PRO =1 THEN B.PRO_RESOURCE ELSE '' END) AS PRO_RESOURCE,
                    MAX(CASE WHEN REC_PRO =1 THEN (SELECT MAX(U.PID) FROM SYS_USER U WHERE U.REAL_NAME=B.OPERATOR) ELSE NULL END) AS CREATER_ID,
                    MAX(CASE WHEN REC_PRO =1 THEN B.UPDATE_DATE ELSE NULL END) AS CREATER_DATE
                     FROM BIZ_LOAN_APPLY_FINANCE_HANDLE B
                     WHERE B.REC_PRO IN (1, 2, 7)
                     GROUP BY B.FINANCE_HANDLE_ID
             ) B
    ON A.PID=B.FINANCE_HANDLE_ID
 WHERE A.STATUS >1;
  C_ROW C_JOB%ROWTYPE;
BEGIN
  FOR C_ROW IN C_JOB LOOP
    INSERT INTO BIZ_LOAN_COLLECT_FEE_HIS
      (PID,
       PROJECT_ID,
       FINANCE_HANDLE_ID,
       CONSULTING_FEE,
       POUNDAGE,
       BROKERAGE,
       REC_DATE,
       PRO_RESOURCE,
       REC_ACCOUNT,
       CREATER_ID,
       CREATER_DATE)
    VALUES
      (SEQ_COLLECT_FEE_HIS.NEXTVAL,
       C_ROW.PROJECT_ID,
       C_ROW.FINANCE_HANDLE_ID,
       C_ROW.CONSULTING_FEE,
       C_ROW.POUNDAGE,
       C_ROW.BROKERAGE,
       C_ROW.REC_DATE,
       C_ROW.PRO_RESOURCE,
       C_ROW.REC_ACCOUNT,
       C_ROW.CREATER_ID,
       C_ROW.CREATER_DATE);
  END LOOP;

END;
/
