
 --修改提交的材料 
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (REQUEST_FILES VARCHAR2(1024));
 --修改公正信息文件
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (LOAN_JUSTICE_FILES VARCHAR2(1024));
 
 --修改卡片信息文件
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (LOAN_BLANK_FILES VARCHAR2(1024));
 --修改其他信息文件 
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (LOAN_OTHER_FILES VARCHAR2(1024));
 
 --修改机构放款凭证
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (PARTNER_LOAN_FILE VARCHAR2(1024));
 
 --修改机构到帐凭证
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (PARTNER_REFUND_FILE VARCHAR2(1024));
 
  