INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '撤单报表', 'xlsx', 12, 1, '', SYSDATE, 1);
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.Nextval,13919,2,15824,1)
