INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '退手续费报表', 'xlsx', 12, 1, '', SYSDATE, 1);

//pid = 15581
  SELECT * FROM BIZ_FILE T WHERE T.FILE_NAME='退手续费报表'; 
 
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.Nextval,13939,2,15581,1)

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '退利息报表', 'xlsx', 12, 1, '', SYSDATE, 1);

//pid = 15582
  SELECT * FROM BIZ_FILE T WHERE T.FILE_NAME='退利息报表'; 
 
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.Nextval,13940,2,15582,1)


INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '退尾款报表', 'xlsx', 12, 1, '', SYSDATE, 1);

//pid = 15583
  SELECT * FROM BIZ_FILE T WHERE T.FILE_NAME='退尾款报表'; 
 
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.Nextval,13941,2,15583,1)


 INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '退手续费报表导出权限',
   '退手续费报表导出权限',
   'REFUND_FEE',
   0,
   1);
  INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '退利息报表导出权限',
   '退利息报表导出权限',
   'REFUND_INTEREST',
   0,
   1);
  INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '退尾款报表导出权限',
   '退尾款报表导出权限',
   'REFUND_TAIL_MONEY',
   0,
   1);