


--修改合作机构编号字段类型
 ALTER TABLE BIZ_PROJECT_PARTNER MODIFY (PARTNER_NO VARCHAR2(50));
 
 --添加借款银行名称
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_BANK  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAYMENT_BANK is '借款银行名称';
 
   --添加 借款银行支行
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_BANK_BRANCH  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAYMENT_BANK_BRANCH is '借款银行支行';
  
  -- 添加借款开户名 
    ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_ACCT_NAME  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAYMENT_ACCT_NAME IS '借款开户名 ';
  
  -- 添加借款开户帐号
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_ACCT_NO  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAYMENT_ACCT_NO IS '借款开户帐号';
  
  --添加 借款银行省份编码
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_PROVINCE_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAYMENT_PROVINCE_CODE is '借款银行省份编码';
  --添加 借款银行城市编码
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAYMENT_CITY_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAYMENT_CITY_CODE is '借款银行城市编码'; 
  
  --添加借款天数
  ALTER TABLE BIZ_PROJECT_PARTNER ADD APPLY_DATE  NUMBER;
  comment on column BIZ_PROJECT_PARTNER.APPLY_DATE is '借款天数'; 
  
  --添加确认放款金额
  ALTER TABLE BIZ_PROJECT_PARTNER ADD CONFIRM_LOAN_MONEY  NUMBER(12,2);
  comment on column BIZ_PROJECT_PARTNER.CONFIRM_LOAN_MONEY is '确认放款金额'; 
  
  --添加确认借款天数
  ALTER TABLE BIZ_PROJECT_PARTNER ADD CONFIRM_LOAN_DAYS  NUMBER;
  comment on column BIZ_PROJECT_PARTNER.CONFIRM_LOAN_DAYS is '确认借款天数'; 
  
  
--添加省市
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PROVINCE_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PROVINCE_CODE is '省份编号';
  ALTER TABLE BIZ_PROJECT_PARTNER ADD CITY_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.CITY_CODE is '城市编号'; 
  
  
--审批放款有效期
  alter table BIZ_PROJECT_PARTNER add LOAN_EFFE_DATE  DATE;
  comment on column BIZ_PROJECT_PARTNER.LOAN_EFFE_DATE is '审批放款有效期';

--机构放款日期
  alter table BIZ_PROJECT_PARTNER add PARTNER_LOAN_DATE  DATE;
  comment on column BIZ_PROJECT_PARTNER.PARTNER_LOAN_DATE is '机构放款日期';

 --机构放款凭证
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PARTNER_LOAN_FILE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PARTNER_LOAN_FILE is '机构放款凭证';

 --修改还款字段备注
 comment on column BIZ_PROJECT_PARTNER.REPAYMENT_REPURCHASE_TYPE is '还款回购类型 ：1：还款  2：回购';
 comment on column BIZ_PROJECT_PARTNER.REPAYMENT_REPURCHASE_STATUS is '还款、回购状态 ：1:未申请2:已申请3:确认收到；4：未收到; 5：确认中';
  
--机构实际还款到帐日
  alter table BIZ_PROJECT_PARTNER add PARTNER_REAL_REFUND_DATE  DATE;
  comment on column BIZ_PROJECT_PARTNER.PARTNER_REAL_REFUND_DATE is '机构实际还款到帐日';
 

 --还款本金
  ALTER TABLE BIZ_PROJECT_PARTNER ADD REFUND_LOAN_AMOUNT  NUMBER(12,2);
  comment on column BIZ_PROJECT_PARTNER.REFUND_LOAN_AMOUNT is '还款本金';
 --还款息费
  ALTER TABLE BIZ_PROJECT_PARTNER ADD REFUND_XIFEE  NUMBER(12,2);
  comment on column BIZ_PROJECT_PARTNER.REFUND_XIFEE is '还款息费';
   
--还款日期
  alter table BIZ_PROJECT_PARTNER add REFUND_DATE  DATE;
  comment on column BIZ_PROJECT_PARTNER.REFUND_DATE is '还款日期';
  
 
 
 
 --机构到帐凭证
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PARTNER_REFUND_FILE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PARTNER_REFUND_FILE is '机构到帐凭证';
 --应补利息金额
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PARTNER_INTERESTS  NUMBER(12,2);
  comment on column BIZ_PROJECT_PARTNER.PARTNER_INTERESTS is '应补利息金额';
  
 --还款、回购备注
  ALTER TABLE BIZ_PROJECT_PARTNER ADD REPAYMENT_REPURCHASE_REMARK  VARCHAR2(255);
  comment on column BIZ_PROJECT_PARTNER.REPAYMENT_REPURCHASE_REMARK is '还款、回购备注';
  
  

  -- 添加还款开户行名（公司）
    ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_BANK_NAME  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAY_BANK_NAME IS '还款银行名称（公司）';
  
  -- 添加还款银行CODE（公司）
    ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_BANK_CODE  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAY_BANK_CODE IS '还款银行CODE（公司）';
  
  
  
   --添加 还款开户行支行
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_BANK_BRANCH  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAY_BANK_BRANCH is '还款银行支行（公司）';
  -- 添加还款账号户名（公司）
    ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_ACCT_NAME  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAY_ACCT_NAME IS '还款账号户名（公司）';
  -- 添加还款帐号（公司）
    ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_ACCT_NO  VARCHAR2(50);
  COMMENT ON COLUMN BIZ_PROJECT_PARTNER.PAY_ACCT_NO IS '还款帐号（公司）';  
  --添加 还款银行省份编码
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_PROVINCE_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAY_PROVINCE_CODE is '还款银行省份编码（公司）';
  --添加 还款银行城市编码
  ALTER TABLE BIZ_PROJECT_PARTNER ADD PAY_CITY_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.PAY_CITY_CODE is '还款银行城市编码（公司）'; 
  
  
--添加物业省份编号
  ALTER TABLE BIZ_PROJECT_PARTNER ADD HOUSE_PROVINCE_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.HOUSE_PROVINCE_CODE is '物业省份编号';
--添加物业城市编号
  ALTER TABLE BIZ_PROJECT_PARTNER ADD HOUSE_CITY_CODE  VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER.HOUSE_CITY_CODE is '物业城市编号'; 
 
 

--修改审批记录字段类型
--不存在数据直接修改  
 ALTER TABLE BIZ_PARTNER_APPROVAL_RECORD MODIFY (LOAN_ID VARCHAR2(55));
--存在数据

  /*修改原字段名LOAN_ID为LOAN_ID_TEMP*/
  ALTER TABLE BIZ_PARTNER_APPROVAL_RECORD RENAME COLUMN LOAN_ID TO LOAN_ID_TEMP;

  /*增加一个和原字段名同名的字段LOAN_ID*/
  ALTER TABLE BIZ_PARTNER_APPROVAL_RECORD ADD LOAN_ID VARCHAR2(55);

  /*将原字段LOAN_ID_TEMP数据更新到增加的字段LOAN_ID*/
  UPDATE BIZ_PARTNER_APPROVAL_RECORD SET   LOAN_ID=trim(LOAN_ID_TEMP);

  /*更新完，删除原字段LOAN_ID_TEMP*/
  ALTER TABLE BIZ_PARTNER_APPROVAL_RECORD DROP COLUMN LOAN_ID_TEMP;
  
  
  comment on column BIZ_PARTNER_APPROVAL_RECORD.LOAN_ID is '审批编号';
  
  
  
  
  -- 项目机构添加文件子类型=============================================================
  ALTER TABLE BIZ_PROJECT_PARTNER_FILE ADD ACCESSORY_CHILD_TYPE VARCHAR2(50);
  comment on column BIZ_PROJECT_PARTNER_FILE.ACCESSORY_CHILD_TYPE is '附件子类型 ';
  
  
  
  
  --客户基本信息添加省市区====================================================================
  --添加省
  ALTER TABLE CUS_PERSON ADD LIVE_PROVINCE_CODE  VARCHAR2(50);
  comment on column CUS_PERSON.LIVE_PROVINCE_CODE is '居住地址省份编号';
  --添加市
  ALTER TABLE CUS_PERSON ADD LIVE_CITY_CODE  VARCHAR2(50);
  comment on column CUS_PERSON.LIVE_CITY_CODE is '居住地址城市编号'; 
  --添加区  
    ALTER TABLE CUS_PERSON ADD LIVE_DISTRICT_CODE  VARCHAR2(50);
  comment on column CUS_PERSON.LIVE_DISTRICT_CODE is '居住地址区编号'; 
  
  
  
  
  
  --机构合作还款表

/*==============================================================*/
/* Table: BIZ_PROJECT_PARTNER_REFUND                            */
/*==============================================================*/
create table BIZ_PROJECT_PARTNER_REFUND 
(
   PID                  INTEGER              PRIMARY KEY,
   PARTNER_ID           INTEGER,
   PROJECT_ID           INTEGER,
   PARTNER_NO           VARCHAR2(50),
   LOAN_ID              VARCHAR2(50),
   CURR_NO              INTEGER,
   CURR_PLAN_REFUND_DATE DATE,
   CURR_SHOULD_CAPITAL_MONEY NUMBER(12,2),
   CURR_SHOULD_XI_FEE   NUMBER(12,2),
   CURR_SHOULD_MANAGE_FEE NUMBER(12,2),
   CURR_SHOULD_OTHER_FEE NUMBER(12,2),
   CURR_SHOULD_TOTAL_MONEY NUMBER(12,2),
   CURR_REAL_REFUND_DATE DATE,
   CURR_REAL_CAPITAL_MONEY NUMBER(12,2),
   CURR_REAL_XI_FEE     NUMBER(12,2),
   CURR_REAL_MANAGE_FEE NUMBER(12,2),
   CURR_REAL_OTHER_FEE  NUMBER(12,2),
   CURR_REAL_TOTAL_MONEY NUMBER(12,2),
   CURR_OVERDUE_STATUS  INTEGER,
   CURR_OVERDUE_DAYS    INTEGER,
   OWE_CAPITAL_MONEY    NUMBER(12,2),
   CURR_CAPITAL_MONEY_FILE VARCHAR2(50),
   CURR_XI_FEE_FILE     VARCHAR2(50),
   IS_SETTLEMENT_STATUS INTEGER,
   IS_FORBIT            INTEGER,
   REFUND_STATUS        INTEGER,
   PARTNER_REAL_REFUND_DATE DATE,
   PARTNER_REFUND_FILE  VARCHAR2(50),
   PARTNER_INTERESTS    NUMBER(12,2),
   REFUND_REMARK		VARCHAR2(1024)
);

comment on table BIZ_PROJECT_PARTNER_REFUND is '项目合作还款表';
comment on column BIZ_PROJECT_PARTNER_REFUND.PID is '主键';
comment on column BIZ_PROJECT_PARTNER_REFUND.PARTNER_ID is '机构项目id';
comment on column BIZ_PROJECT_PARTNER_REFUND.PROJECT_ID is '项目ID';
comment on column BIZ_PROJECT_PARTNER_REFUND.PARTNER_NO is '合作机构编号';
comment on column BIZ_PROJECT_PARTNER_REFUND.LOAN_ID is '第三方贷款ID';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_NO is '当前还款期数';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_PLAN_REFUND_DATE is '当期预计还款日期';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_SHOULD_CAPITAL_MONEY is '当期应还本金金额';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_SHOULD_XI_FEE is '当期应还利息';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_SHOULD_MANAGE_FEE is '当期应还管理费';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_SHOULD_OTHER_FEE is '当期应还其他费用';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_SHOULD_TOTAL_MONEY is '当期还款总金额';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_REFUND_DATE is '实际还款日期';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_CAPITAL_MONEY is '当期实还本金';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_XI_FEE is '当期实还利息';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_MANAGE_FEE is '当期实还管理费';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_OTHER_FEE is '当期实还其他费用';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_REAL_TOTAL_MONEY is '当期实还总金额';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_OVERDUE_STATUS is '当前逾期状态(1:未逾期,2:逾期未结清,3:逾期已结清)';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_OVERDUE_DAYS is '当前逾期天数';
comment on column BIZ_PROJECT_PARTNER_REFUND.OWE_CAPITAL_MONEY is '剩余本金';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_CAPITAL_MONEY_FILE is '还款本金凭证';
comment on column BIZ_PROJECT_PARTNER_REFUND.CURR_XI_FEE_FILE is '还款利息凭证';
comment on column BIZ_PROJECT_PARTNER_REFUND.IS_SETTLEMENT_STATUS is '是否提前结清(1：是 2: 否)';
comment on column BIZ_PROJECT_PARTNER_REFUND.IS_FORBIT is '是否作废(1：是 2: 否)';
comment on column BIZ_PROJECT_PARTNER_REFUND.REFUND_STATUS is '还款状态(1：未申请，2：申请中，3：还款成功，4：还款失败)';
comment on column BIZ_PROJECT_PARTNER_REFUND.PARTNER_REAL_REFUND_DATE is '机构实际还款到帐日';
comment on column BIZ_PROJECT_PARTNER_REFUND.PARTNER_REFUND_FILE is '机构到帐凭证';
comment on column BIZ_PROJECT_PARTNER_REFUND.PARTNER_INTERESTS is '机构应补利息金额';
comment on column BIZ_PROJECT_PARTNER_REFUND.REFUND_REMARK is '还款备注';

  
  
/* 创建序例*/
create sequence SEQ_BIZ_PROJECT_PARTNER_REFUND
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

  
  

 
  