--机构信息管理的按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','新增合作机构信息','新增合作机构信息','ADD_ORG_ASSETS',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改合作机构信息','修改合作机构信息','UPDATE_ORG_ASSETS',0,1);
   
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','认证合作机构','认证合作机构','AUDIT_ORG_ASSETS',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','新增机构合作申请','新增机构合作申请','ADD_ORG_COOPERATE',0,1);
--机构合作申请的按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改机构合作申请','修改机构合作申请','UPDTE_ORG_COOPERATE',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','新增机构保证金变更','新增机构保证金变更','ADD_ORG_FUNDFLOW',0,1);
--保证金变更管理按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改机构保证金变更','修改机构保证金变更','UPDATE_ORG_FUNDFLOW',0,1);

--合伙人信息管理按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','新增合伙人信息','新增合伙人信息','ADD_ORG_PARTNER',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改合伙人信息','修改合伙人信息','UPDATE_ORG_ASSETS',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','认证合伙人','认证合伙人','ADD_AUDIT_PARTNER',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','新增合伙人合作信息','新增合伙人合作信息','ADD_PARTNER_COOPERATE',0,1);
   
--合伙人合作管理按钮权限
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改合伙人合作信息','修改合伙人合作信息','UPDATE_PARTNER_COOPERATE',0,1);

--业务申请管理按钮权限

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','修改业务申请信息','修改业务申请信息','UPDATE_BIZ_PROJECT',0,1);
  
--息费按钮权限

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','上一月的费用结算','上一月的费用结算','CREATE_FEE_SETTLE',0,1);
--机构业务放款导出
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构业务放款数据导出','机构业务放款数据导出','EXPORT_LOAN_PROJECT',0,1);
--机构业务解保导出
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构业务解保数据导出','机构业务解保数据导出','EXPORT_PAYMENT_PROJECT',0,1);
  
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构业务未分配页面分配按钮','机构业务未分配页面分配按钮','ENASSIGNED_BIZ_PROJECT',0,1);

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构业务已分配页面分配按钮','机构业务已分配页面分配按钮','ASSIGNED_BIZ_PROJECT',0,1);

INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构业务驳回按钮','机构业务驳回按钮','REJECT_BIZ_PROJECT',0,1);
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构信息待分配按钮','机构业务待分配按钮','ENALLOCATION_ORG_ASSETS',0,1);
 
INSERT INTO SYS_PERMISSION(PID,PERMIS_TYPE,PERMIS_NAME,PERMIS_DESC,PERMIS_CODE,MENU_ID,STATUS) VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,'CDM','机构信息再分配按钮','机构业务再分配按钮','ALLOCATION_ORG_ASSETS',0,1); 
  
  commit;
--入库放款列表模板数据  
INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,10485,'LOANPROJECTLIST',1,'机构业务放款数据导出模版',sysDate);
commit;

INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '机构业务放款数据报表', 'xlsx', 12, 1, '', SYSDATE, 1);
commit;
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.NEXTVAL,SEQ_SYS_LOOKUP_VAL.CURRVAL,2,SEQ_BIZ_FILE.CURRVAL,1);
commit;

INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.NEXTVAL,SEQ_SYS_LOOKUP_VAL.CURRVAL,2,SEQ_BIZ_FILE.CURRVAL,1);
commit;

INSERT INTO SYS_LOOKUP_VAL (PID,LOOKUP_ID,LOOKUP_VAL,STATUS,LOOKUP_DESC,CREATE_DATETIME)
values(SEQ_SYS_LOOKUP_VAL.NEXTVAL,10485,'CANCLEPROJECTLIST',1,'机构业务解保数据导出模版',SYSDATE);
commit;
INSERT INTO BIZ_FILE(PID,FILE_NAME, FILE_TYPE, FILE_SIZE,UPLOAD_USER_ID, FILE_URL, UPLOAD_DTTM, STATUS)
VALUES (SEQ_BIZ_FILE.NEXTVAL, '机构业务解保数据报表' , 'xlsx', 12, 1, '', SYSDATE, 1);
commit;
INSERT INTO SYS_EXT_TEMPLATE_FILE(PID, TEMPLATE_TYPE, FILE_TYPE, FILE_ID, STATUS)
VALUES(SEQ_SYS_EXT_TEMPLATE_FILE.NEXTVAL,SEQ_SYS_LOOKUP_VAL.CURRVAL,2,SEQ_BIZ_FILE.CURRVAL,1);
commit;

  --添加角色
INSERT INTO SYS_ROLE(PID,ROLE_NAME,ROLE_DESC,ROLE_CODE,STATUS,PARENT_ID) 
values(SEQ_SYS_ROLE.NEXTVAL,'风控委员会','风控委员会','WIND_CONTROL_COMMISSION',1,0);

  --添加角色
INSERT INTO SYS_ROLE(PID,ROLE_NAME,ROLE_DESC,ROLE_CODE,STATUS,PARENT_ID) 
values(SEQ_SYS_ROLE.NEXTVAL,'运营部门人员','运营部门人员','OPERATION_DEPARTMENT_USER',1,0);

INSERT INTO SYS_ROLE(PID,ROLE_NAME,ROLE_DESC,ROLE_CODE,STATUS,PARENT_ID) 
values(SEQ_SYS_ROLE.NEXTVAL,'授信部人员','合作机构合作申请 授信部人员','CREDIT_DEPARTMENT_STAFF',1,0);
commit;

