
 CREATE OR REPLACE VIEW CUS_ACCT_V AS
(
SELECT AC.PID         ACCT_ID,
       PS.CHINA_NAME  ACCT_NAME,
       AC.CUS_TYPE    ACCT_TYPE,
       AC.PM_USER_ID,
       AC.STATUS,
       AC.CUS_STATUS,
       NULL           ECO_TRADE,
       PS.TELEPHONE   TELEPHONE,
       PS.CERT_NUMBER AS CERT_NUMBER,
       PS.MAIL        MAIL,
       PS.UNIT_ADDR   ADDRESS,
       PS.UNIT_CODE   POSTAL_CODE
  FROM CUS_ACCT AC, CUS_PER_BASE PB, CUS_PERSON PS
 WHERE AC.PID = PB.ACCT_ID
   AND PB.ACCT_ID = PS.ACCT_ID
   AND PS.RELATION_TYPE = 1
UNION ALL
SELECT AC.PID,
       CB.CPY_NAME,
       AC.CUS_TYPE,
       AC.PM_USER_ID,
       AC.STATUS,
       AC.CUS_STATUS,
       CB.ECO_TRADE,
       CB.TELEPHONE,
       CB.BUS_LIC_CERT,
       CB.MAIL,
       CB.COMM_ADDR,
       CB.COMM_CODE
  FROM CUS_ACCT AC, CUS_COM_BASE CB
 WHERE AC.PID = CB.ACCT_ID
   AND AC.CUS_TYPE IN(2,3)
 );
--放款增加项目来源明细
--放款增加财务审批工作流
ALTER TABLE BIZ_LOAN_APPLY_FINANCE_HANDLE
ADD (
 PRO_RESOURCE_MONEY           NUMBER(12,2),
 PRO_RESOURCE_MONEY_2         NUMBER(12,2),
 PRO_RESOURCE_2               VARCHAR2(255),
 APPLY_STATUS                 INTEGER DEFAULT 1,
 FUND_MANAGER_REMARK          VARCHAR2(1024),
 FINANCE_DIRECTOR_REMARK      VARCHAR2(1024)
);
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.PRO_RESOURCE
  IS '款项来源1';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.PRO_RESOURCE_MONEY
  IS '款项来源1：金额';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.PRO_RESOURCE_2
  IS '款项来源2';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.PRO_RESOURCE_MONEY_2
  IS '款项来源2：金额';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.FUND_MANAGER_REMARK
  IS '资金主管审批意见';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.FINANCE_DIRECTOR_REMARK
  IS '财务总监审批意见';
COMMENT ON COLUMN BIZ_LOAN_APPLY_FINANCE_HANDLE.APPLY_STATUS
  IS '申请状态：未申请=1,申请中=2,驳回=3,审核中=4,审核通过=5,审核不通过=6,已归档=7'; 
  
COMMENT ON COLUMN BIZ_LOAN_FINANCE_HANDLE.STATUS
  IS '收费状态：未收费=1，已收费=2，已放款=3，放款未完结=4，放款申请中=5';  

UPDATE BIZ_LOAN_APPLY_FINANCE_HANDLE T 
SET T.APPLY_STATUS=5,T.FUND_MANAGER_REMARK='旧数据，无审批意见',T.FINANCE_DIRECTOR_REMARK='旧数据，无审批意见' 
WHERE T.FINANCE_HANDLE_ID IN (SELECT FH.PID FROM BIZ_LOAN_FINANCE_HANDLE FH WHERE FH.STATUS=3);
--增加解保时间字段
ALTER TABLE BIZ_PROJECT
ADD (
 CANCEL_GUARANTEE_DATE           timestamp
);
COMMENT ON COLUMN BIZ_PROJECT.CANCEL_GUARANTEE_DATE
  IS '解保时间';
COMMENT ON COLUMN BIZ_PROJECT.FORECLOSURE_STATUS
  IS '赎楼申请状态1、待客户经理提交2、待部门经理审批3、待业务总监审批4、待审查员审批5、待风控初审6、待风控复审7、待风控终审8、待风控总监审批9、待总经理审批10、已审批11、已放款12、业务办理已完成13、已归档（解保）'; 
--出账单打印权限
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '出账单打印权限',
   '出账单打印权限',
   'MAKE_LOANS_PRINT',
   0,
   1);
--机构收保证金记录权限
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '机构收保证金记录权限',
   '机构收保证金记录权限',
   'ADD_ASSURE_FUND_RECORD',
   0,
   1);
-- 财务放款权限
INSERT INTO SYS_PERMISSION
  (PID,
   PERMIS_TYPE,
   PERMIS_NAME,
   PERMIS_DESC,
   PERMIS_CODE,
   MENU_ID,
   STATUS)
VALUES
  (SEQ_SYS_PERMISSION.NEXTVAL,
   'CDM',
   '财务放款权限',
   '财务放款权限',
   'FINANCE_MAKE_LOANS',
   0,
   1);
